#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019 AS base
WORKDIR /app

# To satisfy VS debugging, put this in the base image
ENV DD_AGENT_HOST=host.docker.internal

# Set environment variables to enable automatic instrumentation
ENV COR_ENABLE_PROFILING=1
ENV COR_PROFILER={846F5F1C-F9AE-4B07-969E-05C26BC060D8}
ENV COR_PROFILER_PATH=/app/datadog/win-x64/Datadog.Trace.ClrProfiler.Native.dll
ENV DD_INTEGRATIONS=/app/datadog/integrations.json
ENV DD_DOTNET_TRACER_HOME=/app/datadog

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["HttpListenerExample.csproj", "./"]
# Also add our nuget.config and packages
COPY ["nuget.config", "./"]
COPY ["packages", "packages"]
RUN dotnet restore "HttpListenerExample.csproj" -r win-x64
COPY . .
WORKDIR "/src"
RUN dotnet build "HttpListenerExample.csproj" -c Release -o /app/build -f net48 -r win-x64

FROM build AS publish
RUN dotnet publish "HttpListenerExample.csproj" -c Release -o /app/publish -f net48 -r win-x64

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
COPY ["*.ps1", "./"]
ENTRYPOINT ["powershell", "./windowsservercore-docker-entrypoint.ps1"]