//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
#pragma warning disable CS8600, CS8601, CS8602, CS8603, CS8604, CS8618, CS8620, CS8714, CS8762, CS8765, CS8766, CS8767, CS8768, CS8769, CS8612, CS8629, CS8774
// Decompiled with JetBrains decompiler
// Type: System.Reflection.Metadata.GenericParameterConstraintHandleCollection
// Assembly: System.Reflection.Metadata, Version=7.0.0.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// MVID: 2EB35F4B-CF50-496F-AFB8-CC6F6F79CB72

using System;
using System.Collections;
using System.Collections.Generic;


#nullable enable
namespace Datadog.Trace.VendoredMicrosoftCode.System.Reflection.Metadata
{
    /// <summary>Represents constraints of a generic type parameter.</summary>
    internal readonly struct GenericParameterConstraintHandleCollection : 
    IReadOnlyList<GenericParameterConstraintHandle>,
    IReadOnlyCollection<GenericParameterConstraintHandle>,
    IEnumerable<GenericParameterConstraintHandle>,
    IEnumerable
  {
    private readonly int _firstRowId;
    private readonly ushort _count;

    internal GenericParameterConstraintHandleCollection(int firstRowId, ushort count)
    {
      this._firstRowId = firstRowId;
      this._count = count;
    }

    public int Count => (int) this._count;

    public GenericParameterConstraintHandle this[int index]
    {
      get
      {
        if (index < 0 || index >= (int) this._count)
          Throw.IndexOutOfRange();
        return GenericParameterConstraintHandle.FromRowId(this._firstRowId + index);
      }
    }

    public GenericParameterConstraintHandleCollection.Enumerator GetEnumerator() => new GenericParameterConstraintHandleCollection.Enumerator(this._firstRowId, this._firstRowId + (int) this._count - 1);


    #nullable disable
    IEnumerator<GenericParameterConstraintHandle> IEnumerable<GenericParameterConstraintHandle>.GetEnumerator() => (IEnumerator<GenericParameterConstraintHandle>) this.GetEnumerator();

    IEnumerator IEnumerable.GetEnumerator() => (IEnumerator) this.GetEnumerator();


    #nullable enable
    internal struct Enumerator : 
      IEnumerator<GenericParameterConstraintHandle>,
      IDisposable,
      IEnumerator
    {
      private readonly int _lastRowId;
      private int _currentRowId;
      private const int EnumEnded = 16777216;

      internal Enumerator(int firstRowId, int lastRowId)
      {
        this._currentRowId = firstRowId - 1;
        this._lastRowId = lastRowId;
      }

      public GenericParameterConstraintHandle Current => GenericParameterConstraintHandle.FromRowId((int) ((long) this._currentRowId & 16777215L));

      public bool MoveNext()
      {
        if (this._currentRowId >= this._lastRowId)
        {
          this._currentRowId = 16777216;
          return false;
        }
        ++this._currentRowId;
        return true;
      }

      object IEnumerator.Current => (object) this.Current;

      void IEnumerator.Reset() => throw new NotSupportedException();

      void IDisposable.Dispose()
      {
      }
    }
  }
}
