//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
#pragma warning disable CS8600, CS8601, CS8602, CS8603, CS8604, CS8618, CS8620, CS8714, CS8762, CS8765, CS8766, CS8767, CS8768, CS8769, CS8612, CS8629, CS8774
// Decompiled with JetBrains decompiler
// Type: System.Reflection.Metadata.GenericParameter
// Assembly: System.Reflection.Metadata, Version=7.0.0.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// MVID: 2EB35F4B-CF50-496F-AFB8-CC6F6F79CB72


#nullable enable
using System.Reflection;

namespace Datadog.Trace.VendoredMicrosoftCode.System.Reflection.Metadata
{
  internal readonly struct GenericParameter
  {

    #nullable disable
    private readonly MetadataReader _reader;
    private readonly int _rowId;


    #nullable enable
    internal GenericParameter(MetadataReader reader, GenericParameterHandle handle)
    {
      this._reader = reader;
      this._rowId = handle.RowId;
    }

    private GenericParameterHandle Handle => GenericParameterHandle.FromRowId(this._rowId);

    /// <summary>
    /// <see cref="T:System.Reflection.Metadata.TypeDefinitionHandle" /> or <see cref="T:System.Reflection.Metadata.MethodDefinitionHandle" />.
    /// </summary>
    /// <remarks>
    /// Corresponds to Owner field of GenericParam table in ECMA-335 Standard.
    /// </remarks>
    public EntityHandle Parent => this._reader.GenericParamTable.GetOwner(this.Handle);

    /// <summary>Attributes specifying variance and constraints.</summary>
    /// <remarks>
    /// Corresponds to Flags field of GenericParam table in ECMA-335 Standard.
    /// </remarks>
    public GenericParameterAttributes Attributes => this._reader.GenericParamTable.GetFlags(this.Handle);

    /// <summary>
    /// Zero-based index of the parameter within the declaring generic type or method declaration.
    /// </summary>
    /// <remarks>
    /// Corresponds to Number field of GenericParam table in ECMA-335 Standard.
    /// </remarks>
    public int Index => (int) this._reader.GenericParamTable.GetNumber(this.Handle);

    /// <summary>The name of the generic parameter.</summary>
    /// <remarks>
    /// Corresponds to Name field of GenericParam table in ECMA-335 Standard.
    /// </remarks>
    public StringHandle Name => this._reader.GenericParamTable.GetName(this.Handle);

    public GenericParameterConstraintHandleCollection GetConstraints() => this._reader.GenericParamConstraintTable.FindConstraintsForGenericParam(this.Handle);

    public CustomAttributeHandleCollection GetCustomAttributes() => new CustomAttributeHandleCollection(this._reader, (EntityHandle) this.Handle);
  }
}
