//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, SYSLIB0011,SYSLIB0032
// dnlib: See LICENSE.txt for more info

using Datadog.Trace.Vendors.dnlib.IO;
using Datadog.Trace.Vendors.dnlib.PE;

namespace Datadog.Trace.Vendors.dnlib.DotNet.Writer {
	/// <summary>
	/// Base class of most heaps
	/// </summary>
	internal abstract class HeapBase : IHeap {
		internal const uint ALIGNMENT = 4;
		FileOffset offset;
		RVA rva;

		/// <summary>
		/// <c>true</c> if <see cref="SetReadOnly"/> has been called
		/// </summary>
		protected bool isReadOnly;

		/// <inheritdoc/>
		public FileOffset FileOffset => offset;

		/// <inheritdoc/>
		public RVA RVA => rva;

		/// <inheritdoc/>
		public abstract string Name { get; }

		/// <inheritdoc/>
		public bool IsEmpty => GetRawLength() <= 1;

		/// <summary>
		/// <c>true</c> if offsets require 4 bytes instead of 2 bytes.
		/// </summary>
		public bool IsBig => GetFileLength() > 0xFFFF;

		/// <inheritdoc/>
		public void SetReadOnly() => isReadOnly = true;

		/// <inheritdoc/>
		public virtual void SetOffset(FileOffset offset, RVA rva) {
			this.offset = offset;
			this.rva = rva;

			// NOTE: This method can be called twice by NativeModuleWriter, see Metadata.SetOffset() for more info
		}

		/// <inheritdoc/>
		public uint GetFileLength() => Utils.AlignUp(GetRawLength(), ALIGNMENT);

		/// <inheritdoc/>
		public uint GetVirtualSize() => GetFileLength();

		/// <summary>
		/// Gets the raw length of the heap
		/// </summary>
		/// <returns>Raw length of the heap</returns>
		public abstract uint GetRawLength();

		/// <inheritdoc/>
		public void WriteTo(DataWriter writer) {
			WriteToImpl(writer);
			writer.WriteZeroes((int)(Utils.AlignUp(GetRawLength(), ALIGNMENT) - GetRawLength()));
		}

		/// <summary>
		/// Writes all data to <paramref name="writer"/> at its current location.
		/// </summary>
		/// <param name="writer">Destination</param>
		protected abstract void WriteToImpl(DataWriter writer);

		/// <inheritdoc/>
		public override string ToString() => Name;
	}
}
