parameters:
  - name: includeX86
    type: boolean
    default: false

steps:
- task: UseDotNet@2
  displayName: install .NET SDK $(dotnetCoreSdkLatestVersion)
  inputs:
    packageType: sdk
    version: $(dotnetCoreSdkLatestVersion)
    includePreviewVersions: true
  retryCountOnTaskFailure: 5

- script: dotnet --info
  displayName: validate .NET SDK $(dotnetCoreSdkLatestVersion) installation

- ${{ if eq(parameters.includeX86, true) }}:
    - template: install-dotnet-sdk-manually.yml
      parameters:
        sdkVersion: $(dotnetCoreSdkLatestVersion)
        is64bit: false
