parameters:
  - name: 'artifact'
    type: 'string'
    default: 'build-windows-working-directory'

steps:
- task: DownloadPipelineArtifact@2
  displayName: Download working dir
  inputs:
    buildType: 'specific'
    project: 'dd-trace-dotnet'
    definition: 54
    buildVersionToDownload: 'specific'
    pipelineId: 170326
    artifact: ${{ parameters.artifact }}
    patterns: "**/@(bin|obj|packages)/**"
    path: $(System.DefaultWorkingDirectory)
  retryCountOnTaskFailure: 5