parameters:
  - name: 'artifact'
    type: 'string'
    default: 'build-windows-working-directory'

steps:
- template: download-artifact.yml
  parameters:
    artifact: ${{ parameters.artifact }}
    path: $(System.DefaultWorkingDirectory)
    retryCountOnTaskFailure: 5