# downloads the working directory and the tracer + profiler home assets from build pipeline 202204
# Beneficial as it can avoid the need to wait for the package stage
parameters:
  - name: 'artifactSuffix'
    type: 'string'
    default: 'linux-x64'

steps:
- task: DownloadPipelineArtifact@2
  displayName: "Download build-${{ parameters.artifactSuffix }}-working-directory"
  inputs:
    buildType: 'specific'
    artifactName: build-${{ parameters.artifactSuffix }}-working-directory
    targetPath: $(System.DefaultWorkingDirectory)
    patterns: "**/@(bin|obj|packages)/**"
    project: 'dd-trace-dotnet'
    definition: 54
    buildVersionToDownload: 'specific'
    pipelineId: 202204

- bash: |
    input="${{ parameters.artifactSuffix }}"
    output="${input/-musl/}"
    echo "setting universalArtifactSuffix to ${output}"
    echo "##vso[task.setvariable variable=universalArtifactSuffix]${output}"

- task: DownloadPipelineArtifact@2
  displayName: "Download linux-universal-home-$(universalArtifactSuffix)"
  inputs:
    buildType: 'specific'
    artifactName: linux-universal-home-$(universalArtifactSuffix)
    targetPath: $(monitoringHome)/${{ parameters.artifactSuffix }}
    project: 'dd-trace-dotnet'
    definition: 54
    buildVersionToDownload: 'specific'
    pipelineId: 202204

- task: DownloadPipelineArtifact@2
  displayName: "Download linux-profiler-home-${{ parameters.artifactSuffix }}"
  inputs:
    buildType: 'specific'
    artifactName: linux-profiler-home-${{ parameters.artifactSuffix }}
    targetPath: $(monitoringHome)
    project: 'dd-trace-dotnet'
    definition: 54
    buildVersionToDownload: 'specific'
    pipelineId: 202204
