<Project>
  <PropertyGroup Condition="'$(MSBuildProjectExtension)' == '.vcxproj'">
    <!-- Suppress warnings from vendored headers without suppressing warnings in Datadog code. -->
    <ExternalIncludePath>$(MSBuildThisFileDirectory)..\..\..\shared\src\native-lib\spdlog\include;$(ExternalIncludePath)</ExternalIncludePath>
  </PropertyGroup>

  <ItemDefinitionGroup Condition="'$(MSBuildProjectExtension)' == '.vcxproj'">
    <ClCompile>
      <ExternalWarningLevel>Level0</ExternalWarningLevel>
    </ClCompile>
  </ItemDefinitionGroup>
</Project>
