//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
#pragma warning disable CS8600, CS8601, CS8602, CS8603, CS8604, CS8618, CS8620, CS8714, CS8762, CS8765, CS8766, CS8767, CS8768, CS8769, CS8612, CS8629, CS8774
#nullable enable
// Decompiled with JetBrains decompiler
// Type: System.Reflection.Metadata.Ecma335.StringHandleType
// Assembly: System.Reflection.Metadata, Version=7.0.0.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// MVID: 2EB35F4B-CF50-496F-AFB8-CC6F6F79CB72

namespace Datadog.Trace.VendoredMicrosoftCode.System.Reflection.Metadata.Ecma335
{
  internal static class StringHandleType
  {
    internal const uint TypeMask = 3758096384;
    internal const uint NonVirtualTypeMask = 1610612736;
    internal const uint String = 0;
    internal const uint DotTerminatedString = 536870912;
    internal const uint ReservedString1 = 1073741824;
    internal const uint ReservedString2 = 1610612736;
    internal const uint VirtualString = 2147483648;
    internal const uint WinRTPrefixedString = 2684354560;
    internal const uint ReservedVirtualString1 = 3221225472;
    internal const uint ReservedVirtualString2 = 3758096384;
  }
}
