//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
#pragma warning disable CS8600, CS8601, CS8602, CS8603, CS8604, CS8618, CS8620, CS8714, CS8762, CS8765, CS8766, CS8767, CS8768, CS8769, CS8612, CS8629, CS8774
#nullable enable
// Decompiled with JetBrains decompiler
// Type: System.Reflection.Metadata.Ecma335.HasFieldMarshalTag
// Assembly: System.Reflection.Metadata, Version=7.0.0.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// MVID: 2EB35F4B-CF50-496F-AFB8-CC6F6F79CB72

using System.Runtime.CompilerServices;

namespace Datadog.Trace.VendoredMicrosoftCode.System.Reflection.Metadata.Ecma335
{
    internal static class HasFieldMarshalTag
  {
    internal const int NumberOfBits = 1;
    internal const int LargeRowSize = 32768;
    internal const uint Field = 0;
    internal const uint Param = 1;
    internal const uint TagMask = 1;
    internal const TableMask TablesReferenced = TableMask.Field | TableMask.Param;
    internal const uint TagToTokenTypeByteVector = 2052;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static EntityHandle ConvertToHandle(uint hasFieldMarshal)
    {
      uint num1 = 2052U >> (((int) hasFieldMarshal & 1) << 3) << 24;
      uint num2 = hasFieldMarshal >> 1;
      if (((int) num2 & -16777216) != 0)
        Throw.InvalidCodedIndex();
      return new EntityHandle(num1 | num2);
    }

    internal static uint ConvertToTag(EntityHandle handle)
    {
      if (handle.Type == 67108864U)
        return (uint) (handle.RowId << 1 | 0);
      return handle.Type == 134217728U ? (uint) (handle.RowId << 1 | 1) : 0U;
    }
  }
}
