<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <SignAssembly>false</SignAssembly>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="OpenFeature" Version="2.3.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
    <ProjectReference Include="../../src/Datadog.FeatureFlags.OpenFeature/Datadog.FeatureFlags.OpenFeature.csproj" />
  </ItemGroup>
</Project>
