include:
  - local: .gitlab/normal-pipeline.yml
    rules:
      - if: '$BP_TRACEANNOTATIONS_CSC_DIAGNOSTIC != "true"'
  - local: .gitlab/benchmarks/microbenchmarks/traceannotations-build-diagnostic.yml
    rules:
      - if: '$BP_TRACEANNOTATIONS_CSC_DIAGNOSTIC == "true"'
