// <copyright file="CompatibilityLayer_CalculateDogStatsDPipeName_Integration.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>

#nullable enable

#if !NETFRAMEWORK
using System;
using System.ComponentModel;
using Datadog.Trace.ClrProfiler.CallTarget;
using Datadog.Trace.Configuration;
using Datadog.Trace.Logging;

namespace Datadog.Trace.ClrProfiler.AutoInstrumentation.Serverless
{
    /// <summary>
    /// Instrumentation for Datadog.Serverless.CompatibilityLayer.CalculateDogStatsDPipeName method.
    /// This instrumentation overrides the return value with the tracer's pre-generated pipe name,
    /// ensuring the tracer's runtime metrics and the compat layer use the same pipe name.
    /// </summary>
    [InstrumentMethod(
        AssemblyName = "Datadog.Serverless.Compat",
        TypeName = "Datadog.Serverless.CompatibilityLayer",
        MethodName = "CalculateDogStatsDPipeName",
        ReturnTypeName = ClrNames.String,
        ParameterTypeNames = new string[0],
        MinimumVersion = "1.0.0",
        MaximumVersion = "2.*.*",
        IntegrationName = nameof(IntegrationId.ServerlessCompat),
        InstrumentationCategory = InstrumentationCategory.Tracing)]
    [Browsable(false)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    public sealed class CompatibilityLayer_CalculateDogStatsDPipeName_Integration
    {
        private static readonly IDatadogLogger Log = DatadogLogging.GetLoggerFor(typeof(CompatibilityLayer_CalculateDogStatsDPipeName_Integration));
        private static readonly object _lock = new object();
        private static string? _cachedDogStatsDPipeName;

        /// <summary>
        /// OnMethodEnd callback - intercepts the return value and overrides it with a lazily-generated unique pipe name
        /// </summary>
        /// <typeparam name="TTarget">Type of the target</typeparam>
        /// <param name="instance">Instance value, aka `this` of the instrumented method (null for static methods)</param>
        /// <param name="returnValue">The pipe name calculated by the compat layer</param>
        /// <param name="exception">Exception instance in case the original code threw an exception</param>
        /// <param name="state">Calltarget state value</param>
        /// <returns>A unique pipe name for coordination between tracer and compat layer</returns>
        internal static CallTargetReturn<string> OnMethodEnd<TTarget>(
            TTarget instance,
            string returnValue,
            Exception exception,
            in CallTargetState state)
        {
            if (exception != null)
            {
                // If there was an exception, pass it through
                return new CallTargetReturn<string>(returnValue);
            }

            try
            {
                // Get the tracer's pipe name (generated in ExporterSettings if on Windows with no explicit config)
                // Use lazy caching to avoid repeated lookups
                if (_cachedDogStatsDPipeName == null)
                {
                    lock (_lock)
                    {
                        if (_cachedDogStatsDPipeName == null)
                        {
                            // Use the pipe name pre-generated by ExporterSettings if available (Azure Functions scenario)
                            // Otherwise, generate a unique pipe name with default base
                            // The tracer controls the pipe name, not the compat layer
                            _cachedDogStatsDPipeName = ExporterSettings.AzureFunctionsGeneratedMetricsPipeName
                                ?? ServerlessCompatPipeNameHelper.GenerateUniquePipeName(
                                    "dd_dogstatsd",
                                    "DogStatsD");
                        }
                    }
                }

                Log.Debug(
                    "ServerlessCompat integration: Overriding compat layer DogStatsD pipe name. " +
                    "Compat layer calculated: {CompatPipeName}, Tracer using: {TracerPipeName}",
                    returnValue,
                    _cachedDogStatsDPipeName);

                return new CallTargetReturn<string>(_cachedDogStatsDPipeName);
            }
            catch (Exception ex)
            {
                Log.Error(ex, "ServerlessCompat integration: Error overriding DogStatsD pipe name");
            }

            // Fallback to compat layer's original value
            return new CallTargetReturn<string>(returnValue);
        }
    }
}
#endif
