//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendoredCode tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// ------------------------------------------------------------
//  Copyright (c) Microsoft Corporation.  All rights reserved.
//  Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.
// ------------------------------------------------------------

using System;
using Datadog.Trace.Vendors.Microsoft.OpenApi.Any;
using Datadog.Trace.Vendors.Microsoft.OpenApi.Interfaces;
using Datadog.Trace.Vendors.Microsoft.OpenApi.Writers;

namespace Datadog.Trace.Vendors.Microsoft.OpenApi.MicrosoftExtensions;

/// <summary>
/// Extension element for OpenAPI to add reserved parameters. x-ms-reserved-parameters
/// </summary>
internal class OpenApiReservedParameterExtension : IOpenApiExtension
{
    /// <summary>
    /// Name of the extension as used in the description.
    /// </summary>
    public static string Name => "x-ms-reserved-parameter";
    /// <inheritdoc />
    public void Write(IOpenApiWriter writer, OpenApiSpecVersion specVersion)
    {
        if (writer is null) throw new ArgumentNullException(nameof(writer));
        if (IsReserved.HasValue)
            writer.WriteValue(IsReserved.Value);
    }
    /// <summary>
    /// Whether the associated parameter is reserved or not.
    /// </summary>
    public bool? IsReserved
    {
        get; set;
    }
    /// <summary>
    /// Parses the <see cref="IOpenApiAny"/> to <see cref="OpenApiReservedParameterExtension"/>.
    /// </summary>
    /// <param name="source">The source object.</param>
    /// <returns>The <see cref="OpenApiReservedParameterExtension"/>.</returns>
    /// <returns></returns>
    public static OpenApiReservedParameterExtension Parse(IOpenApiAny source)
    {
        if (source is not OpenApiBoolean rawBoolean) return null;
        return new()
        {
            IsReserved = rawBoolean.Value
        };
    }
}
