//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendoredCode tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

using Datadog.Trace.Vendors.Microsoft.OpenApi.Attributes;

namespace Datadog.Trace.Vendors.Microsoft.OpenApi.Models
{
    /// <summary>
    /// Operation type.
    /// </summary>
    internal enum OperationType
    {
        /// <summary>
        /// A definition of a GET operation on this path.
        /// </summary>
        [Display("get")] Get,

        /// <summary>
        /// A definition of a PUT operation on this path.
        /// </summary>
        [Display("put")] Put,

        /// <summary>
        /// A definition of a POST operation on this path.
        /// </summary>
        [Display("post")] Post,

        /// <summary>
        /// A definition of a DELETE operation on this path.
        /// </summary>
        [Display("delete")] Delete,

        /// <summary>
        /// A definition of a OPTIONS operation on this path.
        /// </summary>
        [Display("options")] Options,

        /// <summary>
        /// A definition of a HEAD operation on this path.
        /// </summary>
        [Display("head")] Head,

        /// <summary>
        /// A definition of a PATCH operation on this path.
        /// </summary>
        [Display("patch")] Patch,

        /// <summary>
        /// A definition of a TRACE operation on this path.
        /// </summary>
        [Display("trace")] Trace
    }
}
