//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendoredCode tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0023, SYSLIB0032
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

using Datadog.Trace.Vendors.Microsoft.OpenApi.Attributes;

namespace Datadog.Trace.Vendors.Microsoft.OpenApi.Models
{
    /// <summary>
    /// The reference type.
    /// </summary>
    internal enum ReferenceType
    {
        /// <summary>
        /// Schema item.
        /// </summary>
        [Display("schemas")] Schema,

        /// <summary>
        /// Responses item.
        /// </summary>
        [Display("responses")] Response,

        /// <summary>
        /// Parameters item.
        /// </summary>
        [Display("parameters")] Parameter,

        /// <summary>
        /// Examples item.
        /// </summary>
        [Display("examples")] Example,

        /// <summary>
        /// RequestBodies item.
        /// </summary>
        [Display("requestBodies")] RequestBody,

        /// <summary>
        /// Headers item.
        /// </summary>
        [Display("headers")] Header,

        /// <summary>
        /// SecuritySchemes item.
        /// </summary>
        [Display("securitySchemes")] SecurityScheme,

        /// <summary>
        /// Links item.
        /// </summary>
        [Display("links")] Link,

        /// <summary>
        /// Callbacks item.
        /// </summary>
        [Display("callbacks")] Callback,

        /// <summary>
        /// Tags item.
        /// </summary>
        [Display("tags")] Tag,

        /// <summary>
        /// Paths item.
        /// </summary>
        [Display("paths")] Path
    }
}
