<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ApiVersion Condition="'$(ApiVersion)' == ''">1.8.0</ApiVersion>

    <!-- Required to build multiple projects with the same Configuration|Platform, which is needed for the CI library/version matrix -->
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DnsClient" Version="$(ApiVersion)" />
  </ItemGroup>

</Project>
