<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <EnableMSTestRunner>true</EnableMSTestRunner>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <ApiVersion Condition="'$(ApiVersion)' == ''">4.4.0</ApiVersion>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
  </PropertyGroup>
  <ItemGroup>
    <TestingPlatformBuilderHook Include="96FCC592-6643-4B80-A224-46D2F4050C2B">
      <DisplayName>Retry history recorder</DisplayName>
      <TypeFullName>Samples.MSTestTestsNativeRetriesMtp.RetryReporter</TypeFullName>
    </TestingPlatformBuilderHook>
    <Compile Include="../Samples.MSTestTestsNativeRetries/*.cs" Link="%(Filename)%(Extension)" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="$(ApiVersion)" />
    <PackageReference Include="MSTest.TestFramework" Version="$(ApiVersion)" />
  </ItemGroup>
</Project>
