//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendoredCode tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0105, CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0023, SYSLIB0032
#pragma warning disable CS8600, CS8601, CS8602, CS8603, CS8604, CS8618, CS8620, CS8714, CS8762, CS8765, CS8766, CS8767, CS8768, CS8769, CS8612, CS8629, CS8774
#nullable enable
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

#nullable enable
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;

namespace Datadog.Trace.VendoredMicrosoftCode.System.Reflection.Metadata
{
    [Flags]
    internal enum MetadataReaderOptions
    {
        /// <summary>
        /// All options are disabled.
        /// </summary>
        None = 0x0,

        /// <summary>
        /// The options that are used when a <see cref="MetadataReader"/> is obtained
        /// via an overload that does not take a <see cref="MetadataReaderOptions"/>
        /// argument.
        /// </summary>
        Default = ApplyWindowsRuntimeProjections,

        /// <summary>
        /// Windows Runtime projections are enabled (on by default).
        /// </summary>
        ApplyWindowsRuntimeProjections = 0x1
    }
}
