name: 'Deploy AAS dev app'
description: 'Deploy AAS dev app'

inputs:
  github_token:
    description: 'GitHub token with permissions to dispatch to datadog-aas-extension'
    required: true

runs:
  using: "composite"
  steps:
    - name: Trigger AAS deploy
      shell: bash
      run: |
        curl -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: Bearer ${{ inputs.github_token }}" \
        https://api.github.com/repos/DataDog/datadog-aas-extension/dispatches \
        -d '{"event_type": "dd-trace-dotnet-nightly", "client_payload": {"sha":"'"$GITHUB_SHA"'" } }'
