//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendoredCode tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0023, SYSLIB0032
#nullable enable
// <copyright file="ISerializable.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2022 Datadog, Inc.
// </copyright>

namespace Datadog.Trace.Vendors.Datadog.Sketches.Serialization
{
    /// <summary>
    /// Object serializable to protobuf using the dedicated serializer
    /// </summary>
    internal interface ISerializable
    {
        /// <summary>
        /// Gets the needed size for serialization
        /// </summary>
        int ComputeSerializedSize();

        /// <summary>
        /// Serialize to protobuf using the given serializer
        /// </summary>
        /// <param name="serializer">Serializer used to manually encode the object to protobuf</param>
        void Serialize(Serializer serializer);
    }
}
