// <copyright file="Constants.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>

namespace Datadog.Trace.SourceGenerators;

internal static class Constants
{
    public const string Usage = nameof(Usage);

    public const string FileHeader =
        """
        // <copyright company="Datadog">
        // Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
        // This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
        // </copyright>
        // <auto-generated/>
        
        #nullable enable
        
        
        """;
}
