#if NETCOREAPP3_0_OR_GREATER
using System;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;

namespace Samples.Probes.TestRuns.ExceptionReplay
{
    /// <summary>
    /// Uses an anonymous type with 300 DateTime properties, i.e. a generic instantiation (about 3 bytes per type argument)
    /// whose signature is far larger than the 500 byte buffers the native tracer used to copy it into.
    /// <see cref="ThrowWithLargeLocal"/> holds it as a local and the lambda that throws returns it, so Exception Replay
    /// rewrites one method with a large local and one with a large return type. Either used to overflow a stack buffer
    /// in the native tracer and fail fast the process.
    /// No probe or ExceptionReplay attributes: ProbesTests skips it, and it stays out of the snapshot suite.
    /// </summary>
    public class LargeAnonymousTypeTest : IAsyncRun
    {
        public Task RunAsync()
        {
            ThrowWithLargeLocal();
            return Task.CompletedTask;
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        private static void ThrowWithLargeLocal()
        {
            var large = new
            {
                P0 = DateTime.MinValue,
                P1 = DateTime.MinValue,
                P2 = DateTime.MinValue,
                P3 = DateTime.MinValue,
                P4 = DateTime.MinValue,
                P5 = DateTime.MinValue,
                P6 = DateTime.MinValue,
                P7 = DateTime.MinValue,
                P8 = DateTime.MinValue,
                P9 = DateTime.MinValue,
                P10 = DateTime.MinValue,
                P11 = DateTime.MinValue,
                P12 = DateTime.MinValue,
                P13 = DateTime.MinValue,
                P14 = DateTime.MinValue,
                P15 = DateTime.MinValue,
                P16 = DateTime.MinValue,
                P17 = DateTime.MinValue,
                P18 = DateTime.MinValue,
                P19 = DateTime.MinValue,
                P20 = DateTime.MinValue,
                P21 = DateTime.MinValue,
                P22 = DateTime.MinValue,
                P23 = DateTime.MinValue,
                P24 = DateTime.MinValue,
                P25 = DateTime.MinValue,
                P26 = DateTime.MinValue,
                P27 = DateTime.MinValue,
                P28 = DateTime.MinValue,
                P29 = DateTime.MinValue,
                P30 = DateTime.MinValue,
                P31 = DateTime.MinValue,
                P32 = DateTime.MinValue,
                P33 = DateTime.MinValue,
                P34 = DateTime.MinValue,
                P35 = DateTime.MinValue,
                P36 = DateTime.MinValue,
                P37 = DateTime.MinValue,
                P38 = DateTime.MinValue,
                P39 = DateTime.MinValue,
                P40 = DateTime.MinValue,
                P41 = DateTime.MinValue,
                P42 = DateTime.MinValue,
                P43 = DateTime.MinValue,
                P44 = DateTime.MinValue,
                P45 = DateTime.MinValue,
                P46 = DateTime.MinValue,
                P47 = DateTime.MinValue,
                P48 = DateTime.MinValue,
                P49 = DateTime.MinValue,
                P50 = DateTime.MinValue,
                P51 = DateTime.MinValue,
                P52 = DateTime.MinValue,
                P53 = DateTime.MinValue,
                P54 = DateTime.MinValue,
                P55 = DateTime.MinValue,
                P56 = DateTime.MinValue,
                P57 = DateTime.MinValue,
                P58 = DateTime.MinValue,
                P59 = DateTime.MinValue,
                P60 = DateTime.MinValue,
                P61 = DateTime.MinValue,
                P62 = DateTime.MinValue,
                P63 = DateTime.MinValue,
                P64 = DateTime.MinValue,
                P65 = DateTime.MinValue,
                P66 = DateTime.MinValue,
                P67 = DateTime.MinValue,
                P68 = DateTime.MinValue,
                P69 = DateTime.MinValue,
                P70 = DateTime.MinValue,
                P71 = DateTime.MinValue,
                P72 = DateTime.MinValue,
                P73 = DateTime.MinValue,
                P74 = DateTime.MinValue,
                P75 = DateTime.MinValue,
                P76 = DateTime.MinValue,
                P77 = DateTime.MinValue,
                P78 = DateTime.MinValue,
                P79 = DateTime.MinValue,
                P80 = DateTime.MinValue,
                P81 = DateTime.MinValue,
                P82 = DateTime.MinValue,
                P83 = DateTime.MinValue,
                P84 = DateTime.MinValue,
                P85 = DateTime.MinValue,
                P86 = DateTime.MinValue,
                P87 = DateTime.MinValue,
                P88 = DateTime.MinValue,
                P89 = DateTime.MinValue,
                P90 = DateTime.MinValue,
                P91 = DateTime.MinValue,
                P92 = DateTime.MinValue,
                P93 = DateTime.MinValue,
                P94 = DateTime.MinValue,
                P95 = DateTime.MinValue,
                P96 = DateTime.MinValue,
                P97 = DateTime.MinValue,
                P98 = DateTime.MinValue,
                P99 = DateTime.MinValue,
                P100 = DateTime.MinValue,
                P101 = DateTime.MinValue,
                P102 = DateTime.MinValue,
                P103 = DateTime.MinValue,
                P104 = DateTime.MinValue,
                P105 = DateTime.MinValue,
                P106 = DateTime.MinValue,
                P107 = DateTime.MinValue,
                P108 = DateTime.MinValue,
                P109 = DateTime.MinValue,
                P110 = DateTime.MinValue,
                P111 = DateTime.MinValue,
                P112 = DateTime.MinValue,
                P113 = DateTime.MinValue,
                P114 = DateTime.MinValue,
                P115 = DateTime.MinValue,
                P116 = DateTime.MinValue,
                P117 = DateTime.MinValue,
                P118 = DateTime.MinValue,
                P119 = DateTime.MinValue,
                P120 = DateTime.MinValue,
                P121 = DateTime.MinValue,
                P122 = DateTime.MinValue,
                P123 = DateTime.MinValue,
                P124 = DateTime.MinValue,
                P125 = DateTime.MinValue,
                P126 = DateTime.MinValue,
                P127 = DateTime.MinValue,
                P128 = DateTime.MinValue,
                P129 = DateTime.MinValue,
                P130 = DateTime.MinValue,
                P131 = DateTime.MinValue,
                P132 = DateTime.MinValue,
                P133 = DateTime.MinValue,
                P134 = DateTime.MinValue,
                P135 = DateTime.MinValue,
                P136 = DateTime.MinValue,
                P137 = DateTime.MinValue,
                P138 = DateTime.MinValue,
                P139 = DateTime.MinValue,
                P140 = DateTime.MinValue,
                P141 = DateTime.MinValue,
                P142 = DateTime.MinValue,
                P143 = DateTime.MinValue,
                P144 = DateTime.MinValue,
                P145 = DateTime.MinValue,
                P146 = DateTime.MinValue,
                P147 = DateTime.MinValue,
                P148 = DateTime.MinValue,
                P149 = DateTime.MinValue,
                P150 = DateTime.MinValue,
                P151 = DateTime.MinValue,
                P152 = DateTime.MinValue,
                P153 = DateTime.MinValue,
                P154 = DateTime.MinValue,
                P155 = DateTime.MinValue,
                P156 = DateTime.MinValue,
                P157 = DateTime.MinValue,
                P158 = DateTime.MinValue,
                P159 = DateTime.MinValue,
                P160 = DateTime.MinValue,
                P161 = DateTime.MinValue,
                P162 = DateTime.MinValue,
                P163 = DateTime.MinValue,
                P164 = DateTime.MinValue,
                P165 = DateTime.MinValue,
                P166 = DateTime.MinValue,
                P167 = DateTime.MinValue,
                P168 = DateTime.MinValue,
                P169 = DateTime.MinValue,
                P170 = DateTime.MinValue,
                P171 = DateTime.MinValue,
                P172 = DateTime.MinValue,
                P173 = DateTime.MinValue,
                P174 = DateTime.MinValue,
                P175 = DateTime.MinValue,
                P176 = DateTime.MinValue,
                P177 = DateTime.MinValue,
                P178 = DateTime.MinValue,
                P179 = DateTime.MinValue,
                P180 = DateTime.MinValue,
                P181 = DateTime.MinValue,
                P182 = DateTime.MinValue,
                P183 = DateTime.MinValue,
                P184 = DateTime.MinValue,
                P185 = DateTime.MinValue,
                P186 = DateTime.MinValue,
                P187 = DateTime.MinValue,
                P188 = DateTime.MinValue,
                P189 = DateTime.MinValue,
                P190 = DateTime.MinValue,
                P191 = DateTime.MinValue,
                P192 = DateTime.MinValue,
                P193 = DateTime.MinValue,
                P194 = DateTime.MinValue,
                P195 = DateTime.MinValue,
                P196 = DateTime.MinValue,
                P197 = DateTime.MinValue,
                P198 = DateTime.MinValue,
                P199 = DateTime.MinValue,
                P200 = DateTime.MinValue,
                P201 = DateTime.MinValue,
                P202 = DateTime.MinValue,
                P203 = DateTime.MinValue,
                P204 = DateTime.MinValue,
                P205 = DateTime.MinValue,
                P206 = DateTime.MinValue,
                P207 = DateTime.MinValue,
                P208 = DateTime.MinValue,
                P209 = DateTime.MinValue,
                P210 = DateTime.MinValue,
                P211 = DateTime.MinValue,
                P212 = DateTime.MinValue,
                P213 = DateTime.MinValue,
                P214 = DateTime.MinValue,
                P215 = DateTime.MinValue,
                P216 = DateTime.MinValue,
                P217 = DateTime.MinValue,
                P218 = DateTime.MinValue,
                P219 = DateTime.MinValue,
                P220 = DateTime.MinValue,
                P221 = DateTime.MinValue,
                P222 = DateTime.MinValue,
                P223 = DateTime.MinValue,
                P224 = DateTime.MinValue,
                P225 = DateTime.MinValue,
                P226 = DateTime.MinValue,
                P227 = DateTime.MinValue,
                P228 = DateTime.MinValue,
                P229 = DateTime.MinValue,
                P230 = DateTime.MinValue,
                P231 = DateTime.MinValue,
                P232 = DateTime.MinValue,
                P233 = DateTime.MinValue,
                P234 = DateTime.MinValue,
                P235 = DateTime.MinValue,
                P236 = DateTime.MinValue,
                P237 = DateTime.MinValue,
                P238 = DateTime.MinValue,
                P239 = DateTime.MinValue,
                P240 = DateTime.MinValue,
                P241 = DateTime.MinValue,
                P242 = DateTime.MinValue,
                P243 = DateTime.MinValue,
                P244 = DateTime.MinValue,
                P245 = DateTime.MinValue,
                P246 = DateTime.MinValue,
                P247 = DateTime.MinValue,
                P248 = DateTime.MinValue,
                P249 = DateTime.MinValue,
                P250 = DateTime.MinValue,
                P251 = DateTime.MinValue,
                P252 = DateTime.MinValue,
                P253 = DateTime.MinValue,
                P254 = DateTime.MinValue,
                P255 = DateTime.MinValue,
                P256 = DateTime.MinValue,
                P257 = DateTime.MinValue,
                P258 = DateTime.MinValue,
                P259 = DateTime.MinValue,
                P260 = DateTime.MinValue,
                P261 = DateTime.MinValue,
                P262 = DateTime.MinValue,
                P263 = DateTime.MinValue,
                P264 = DateTime.MinValue,
                P265 = DateTime.MinValue,
                P266 = DateTime.MinValue,
                P267 = DateTime.MinValue,
                P268 = DateTime.MinValue,
                P269 = DateTime.MinValue,
                P270 = DateTime.MinValue,
                P271 = DateTime.MinValue,
                P272 = DateTime.MinValue,
                P273 = DateTime.MinValue,
                P274 = DateTime.MinValue,
                P275 = DateTime.MinValue,
                P276 = DateTime.MinValue,
                P277 = DateTime.MinValue,
                P278 = DateTime.MinValue,
                P279 = DateTime.MinValue,
                P280 = DateTime.MinValue,
                P281 = DateTime.MinValue,
                P282 = DateTime.MinValue,
                P283 = DateTime.MinValue,
                P284 = DateTime.MinValue,
                P285 = DateTime.MinValue,
                P286 = DateTime.MinValue,
                P287 = DateTime.MinValue,
                P288 = DateTime.MinValue,
                P289 = DateTime.MinValue,
                P290 = DateTime.MinValue,
                P291 = DateTime.MinValue,
                P292 = DateTime.MinValue,
                P293 = DateTime.MinValue,
                P294 = DateTime.MinValue,
                P295 = DateTime.MinValue,
                P296 = DateTime.MinValue,
                P297 = DateTime.MinValue,
                P298 = DateTime.MinValue,
                P299 = DateTime.MinValue
            };

            Consume(large.P0.Year + large.P299.Month);

            var throwingFactory = AsFactory(large, () => throw new ExceptionReplayIntentionalException("large anonymous type"));
            throwingFactory();
        }

        // Infers T from the prototype so the lambda passed in returns the anonymous type
        private static Func<T> AsFactory<T>(T prototype, Func<T> factory) => factory;

        [MethodImpl(MethodImplOptions.NoInlining)]
        private static void Consume(int value)
        {
            if (value < 0)
            {
                Console.WriteLine(value);
            }
        }
    }
}
#endif
