//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendoredCode tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0023, SYSLIB0032
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

using Datadog.Trace.Vendors.Microsoft.OpenApi.Exceptions;
using Datadog.Trace.Vendors.Microsoft.OpenApi.Models;

namespace Datadog.Trace.Vendors.Microsoft.OpenApi.Services
{
    /// <summary>
    /// 
    /// </summary>
    internal class OpenApiReferenceError : OpenApiError
    {
        private OpenApiReference _reference;
        /// <summary>
        /// Initializes the <see cref="OpenApiError"/> class using the message and pointer from the given exception.
        /// </summary>
        public OpenApiReferenceError(OpenApiException exception) : base(exception.Pointer, exception.Message)
        {
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="reference"></param>
        /// <param name="message"></param>
        public OpenApiReferenceError(OpenApiReference reference, string message) : base("", message)
        {
            _reference = reference;
        }
    }
}
