//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendoredCode tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

using Datadog.Trace.Vendors.Microsoft.OpenApi.Writers;

namespace Datadog.Trace.Vendors.Microsoft.OpenApi.Interfaces
{
    /// <summary>
    /// Represents an Open API element that comes with serialization functionality.
    /// </summary>
    internal interface IOpenApiSerializable : IOpenApiElement
    {
        /// <summary>
        /// Serialize Open API element to v3.0.
        /// </summary>
        /// <param name="writer">The writer.</param>
        void SerializeAsV3(IOpenApiWriter writer);

        /// <summary>
        /// Serialize Open API element to v2.0.
        /// </summary>
        /// <param name="writer">The writer.</param>
        void SerializeAsV2(IOpenApiWriter writer);
    }
}
