// <copyright file="InstrumentationDefinitions.Generated.cs" company="Datadog">
// Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2 License.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2017 Datadog, Inc.
// </copyright>

using System.Collections.Generic;

namespace Datadog.Trace.ClrProfiler
{
    internal static partial class InstrumentationDefinitions
    {
        private static List<NativeCallTargetDefinition> GetDefinitionsList()
        {
            List<NativeCallTargetDefinition> definitionList = new List<NativeCallTargetDefinition>();

            // AdoNet
            definitionList.Add(new("System.Data", "System.Data.Common.DbCommand", "ExecuteDbDataReaderAsync",  new[] { "System.Threading.Tasks.Task`1<System.Data.Common.DbDataReader>", "System.Data.CommandBehavior", "System.Threading.CancellationToken" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorAndCancellationAsyncIntegration"));
            definitionList.Add(new("System.Data", "System.Data.Common.DbCommand", "ExecuteNonQueryAsync",  new[] { "System.Threading.Tasks.Task`1<System.Int32>", "System.Threading.CancellationToken" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteNonQueryAsyncIntegration"));
            definitionList.Add(new("System.Data", "System.Data.Common.DbCommand", "ExecuteScalarAsync",  new[] { "System.Threading.Tasks.Task`1<System.Object>", "System.Threading.CancellationToken" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteScalarAsyncIntegration"));
            definitionList.Add(new("System.Data.Common", "System.Data.Common.DbCommand", "ExecuteDbDataReaderAsync",  new[] { "System.Threading.Tasks.Task`1<System.Data.Common.DbDataReader>", "System.Data.CommandBehavior", "System.Threading.CancellationToken" }, 4, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorAndCancellationAsyncIntegration"));
            definitionList.Add(new("System.Data.Common", "System.Data.Common.DbCommand", "ExecuteNonQueryAsync",  new[] { "System.Threading.Tasks.Task`1<System.Int32>", "System.Threading.CancellationToken" }, 4, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteNonQueryAsyncIntegration"));
            definitionList.Add(new("System.Data.Common", "System.Data.Common.DbCommand", "ExecuteScalarAsync",  new[] { "System.Threading.Tasks.Task`1<System.Object>", "System.Threading.CancellationToken" }, 4, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteScalarAsyncIntegration"));

            // Aerospike
            definitionList.Add(new("AerospikeClient", "Aerospike.Client.AsyncCommand", "ExecuteCommand",  new[] { "System.Void" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Aerospike.AsyncCommandIntegration"));
            definitionList.Add(new("AerospikeClient", "Aerospike.Client.SyncCommand", "ExecuteCommand",  new[] { "System.Void" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Aerospike.SyncCommandIntegration"));

            // AspNet
            definitionList.Add(new("System.Web", "System.Web.ThreadContext", "AssociateWithCurrentThread",  new[] { "System.Void", "System.Boolean" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AspNet.ThreadContext_AssociateWithCurrentThread_Integration"));
            definitionList.Add(new("System.Web", "System.Web.ThreadContext", "DisassociateFromCurrentThread",  new[] { "System.Void" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AspNet.ThreadContext_DisassociateFromCurrentThread_Integration"));

            // AspNetWebApi2
            definitionList.Add(new("System.Web.Http", "System.Web.Http.ExceptionHandling.ExceptionHandlerExtensions", "HandleAsync",  new[] { "System.Threading.Tasks.Task`1<System.Net.Http.HttpResponseMessage>", "System.Web.Http.ExceptionHandling.IExceptionHandler", "System.Web.Http.ExceptionHandling.ExceptionContext", "System.Threading.CancellationToken" }, 5, 1, 0, 5, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AspNet.ExceptionHandlerExtensions_HandleAsync_Integration"));

            // AwsSdk
            definitionList.Add(new("AWSSDK.Core", "Amazon.Runtime.Internal.RuntimePipeline", "InvokeAsync",  new[] { "System.Threading.Tasks.Task`1<T>", "Amazon.Runtime.IExecutionContext" }, 3, 0, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AWS.SDK.RuntimePipelineInvokeAsyncIntegration"));
            definitionList.Add(new("AWSSDK.Core", "Amazon.Runtime.Internal.RuntimePipeline", "InvokeSync",  new[] { "Amazon.Runtime.IResponseContext", "Amazon.Runtime.IExecutionContext" }, 3, 0, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AWS.SDK.RuntimePipelineInvokeSyncIntegration"));

            // AwsSqs
            definitionList.Add(new("AWSSDK.SQS", "Amazon.SQS.AmazonSQSClient", "CreateQueue",  new[] { "Amazon.SQS.Model.CreateQueueResponse", "Amazon.SQS.Model.CreateQueueRequest" }, 3, 0, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AWS.SQS.CreateQueueIntegration"));
            definitionList.Add(new("AWSSDK.SQS", "Amazon.SQS.AmazonSQSClient", "CreateQueueAsync",  new[] { "System.Threading.Tasks.Task`1<Amazon.SQS.Model.CreateQueueResponse>", "Amazon.SQS.Model.CreateQueueRequest", "System.Threading.CancellationToken" }, 3, 0, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AWS.SQS.CreateQueueAsyncIntegration"));
            definitionList.Add(new("AWSSDK.SQS", "Amazon.SQS.AmazonSQSClient", "DeleteMessage",  new[] { "Amazon.SQS.Model.DeleteMessageResponse", "Amazon.SQS.Model.DeleteMessageRequest" }, 3, 0, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AWS.SQS.DeleteMessageIntegration"));
            definitionList.Add(new("AWSSDK.SQS", "Amazon.SQS.AmazonSQSClient", "DeleteMessageAsync",  new[] { "System.Threading.Tasks.Task`1<Amazon.SQS.Model.DeleteMessageResponse>", "Amazon.SQS.Model.DeleteMessageRequest", "System.Threading.CancellationToken" }, 3, 0, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AWS.SQS.DeleteMessageAsyncIntegration"));
            definitionList.Add(new("AWSSDK.SQS", "Amazon.SQS.AmazonSQSClient", "DeleteMessageBatch",  new[] { "Amazon.SQS.Model.DeleteMessageBatchResponse", "Amazon.SQS.Model.DeleteMessageBatchRequest" }, 3, 0, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AWS.SQS.DeleteMessageBatchIntegration"));
            definitionList.Add(new("AWSSDK.SQS", "Amazon.SQS.AmazonSQSClient", "DeleteMessageBatchAsync",  new[] { "System.Threading.Tasks.Task`1<Amazon.SQS.Model.DeleteMessageBatchResponse>", "Amazon.SQS.Model.DeleteMessageBatchRequest", "System.Threading.CancellationToken" }, 3, 0, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AWS.SQS.DeleteMessageBatchAsyncIntegration"));
            definitionList.Add(new("AWSSDK.SQS", "Amazon.SQS.AmazonSQSClient", "DeleteQueue",  new[] { "Amazon.SQS.Model.DeleteQueueResponse", "Amazon.SQS.Model.DeleteQueueRequest" }, 3, 0, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AWS.SQS.DeleteQueueIntegration"));
            definitionList.Add(new("AWSSDK.SQS", "Amazon.SQS.AmazonSQSClient", "DeleteQueueAsync",  new[] { "System.Threading.Tasks.Task`1<Amazon.SQS.Model.DeleteQueueResponse>", "Amazon.SQS.Model.DeleteQueueRequest", "System.Threading.CancellationToken" }, 3, 0, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AWS.SQS.DeleteQueueAsyncIntegration"));
            definitionList.Add(new("AWSSDK.SQS", "Amazon.SQS.AmazonSQSClient", "ReceiveMessage",  new[] { "Amazon.SQS.Model.ReceiveMessageResponse", "Amazon.SQS.Model.ReceiveMessageRequest" }, 3, 0, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AWS.SQS.ReceiveMessageIntegration"));
            definitionList.Add(new("AWSSDK.SQS", "Amazon.SQS.AmazonSQSClient", "ReceiveMessageAsync",  new[] { "System.Threading.Tasks.Task`1<Amazon.SQS.Model.ReceiveMessageResponse>", "Amazon.SQS.Model.ReceiveMessageRequest", "System.Threading.CancellationToken" }, 3, 0, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AWS.SQS.ReceiveMessageAsyncIntegration"));
            definitionList.Add(new("AWSSDK.SQS", "Amazon.SQS.AmazonSQSClient", "SendMessage",  new[] { "Amazon.SQS.Model.SendMessageResponse", "Amazon.SQS.Model.SendMessageRequest" }, 3, 0, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AWS.SQS.SendMessageIntegration"));
            definitionList.Add(new("AWSSDK.SQS", "Amazon.SQS.AmazonSQSClient", "SendMessageAsync",  new[] { "System.Threading.Tasks.Task`1<Amazon.SQS.Model.SendMessageResponse>", "Amazon.SQS.Model.SendMessageRequest", "System.Threading.CancellationToken" }, 3, 0, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AWS.SQS.SendMessageAsyncIntegration"));
            definitionList.Add(new("AWSSDK.SQS", "Amazon.SQS.AmazonSQSClient", "SendMessageBatch",  new[] { "Amazon.SQS.Model.SendMessageBatchResponse", "Amazon.SQS.Model.SendMessageBatchRequest" }, 3, 0, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AWS.SQS.SendMessageBatchIntegration"));
            definitionList.Add(new("AWSSDK.SQS", "Amazon.SQS.AmazonSQSClient", "SendMessageBatchAsync",  new[] { "System.Threading.Tasks.Task`1<Amazon.SQS.Model.SendMessageBatchResponse>", "Amazon.SQS.Model.SendMessageBatchRequest", "System.Threading.CancellationToken" }, 3, 0, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AWS.SQS.SendMessageBatchAsyncIntegration"));

            // AzureFunctions
            definitionList.Add(new("Microsoft.Azure.WebJobs.Host", "Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor", "TryExecuteAsync",  new[] { "System.Threading.Tasks.Task`1[Microsoft.Azure.WebJobs.Host.Executors.IDelayedException]", "Microsoft.Azure.WebJobs.Host.Executors.IFunctionInstance", "System.Threading.CancellationToken" }, 3, 0, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Azure.Functions.AzureFunctionsExecutorTryExecuteAsyncIntegration"));
            definitionList.Add(new("Microsoft.Azure.WebJobs.Script.WebHost", "Microsoft.Azure.WebJobs.Script.WebHost.Middleware.FunctionInvocationMiddleware", "Invoke",  new[] { "System.Threading.Tasks.Task", "Microsoft.AspNetCore.Http.HttpContext" }, 3, 0, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Azure.Functions.FunctionInvocationMiddlewareInvokeIntegration"));

            // CosmosDb
            definitionList.Add(new("Microsoft.Azure.Cosmos.Client", "Microsoft.Azure.Cosmos.ContainerCore", "GetItemQueryIterator",  new[] { "Microsoft.Azure.Cosmos.FeedIterator`1<T>", "Microsoft.Azure.Cosmos.QueryDefinition", "System.String", "Microsoft.Azure.Cosmos.QueryRequestOptions" }, 3, 6, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.CosmosDb.ContainerQueryIteratorsIntegrations"));
            definitionList.Add(new("Microsoft.Azure.Cosmos.Client", "Microsoft.Azure.Cosmos.ContainerCore", "GetItemQueryIterator",  new[] { "Microsoft.Azure.Cosmos.FeedIterator`1<T>", "System.String", "System.String", "Microsoft.Azure.Cosmos.QueryRequestOptions" }, 3, 6, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.CosmosDb.ContainerQueryIteratorsIntegrations"));
            definitionList.Add(new("Microsoft.Azure.Cosmos.Client", "Microsoft.Azure.Cosmos.ContainerCore", "GetItemQueryStreamIterator",  new[] { "Microsoft.Azure.Cosmos.FeedIterator`1<T>", "Microsoft.Azure.Cosmos.QueryDefinition", "System.String", "Microsoft.Azure.Cosmos.QueryRequestOptions" }, 3, 6, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.CosmosDb.ContainerQueryIteratorsIntegrations"));
            definitionList.Add(new("Microsoft.Azure.Cosmos.Client", "Microsoft.Azure.Cosmos.ContainerCore", "GetItemQueryStreamIterator",  new[] { "Microsoft.Azure.Cosmos.FeedIterator`1<T>", "System.String", "System.String", "Microsoft.Azure.Cosmos.QueryRequestOptions" }, 3, 6, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.CosmosDb.ContainerQueryIteratorsIntegrations"));
            definitionList.Add(new("Microsoft.Azure.Cosmos.Client", "Microsoft.Azure.Cosmos.CosmosClient", "GetDatabaseQueryIterator",  new[] { "Microsoft.Azure.Cosmos.FeedIterator`1<T>", "Microsoft.Azure.Cosmos.QueryDefinition", "System.String", "Microsoft.Azure.Cosmos.QueryRequestOptions" }, 3, 6, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.CosmosDb.ClientQueryIteratorsIntegrations"));
            definitionList.Add(new("Microsoft.Azure.Cosmos.Client", "Microsoft.Azure.Cosmos.CosmosClient", "GetDatabaseQueryIterator",  new[] { "Microsoft.Azure.Cosmos.FeedIterator`1<T>", "System.String", "System.String", "Microsoft.Azure.Cosmos.QueryRequestOptions" }, 3, 6, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.CosmosDb.ClientQueryIteratorsIntegrations"));
            definitionList.Add(new("Microsoft.Azure.Cosmos.Client", "Microsoft.Azure.Cosmos.CosmosClient", "GetDatabaseQueryStreamIterator",  new[] { "Microsoft.Azure.Cosmos.FeedIterator`1<T>", "Microsoft.Azure.Cosmos.QueryDefinition", "System.String", "Microsoft.Azure.Cosmos.QueryRequestOptions" }, 3, 6, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.CosmosDb.ClientQueryIteratorsIntegrations"));
            definitionList.Add(new("Microsoft.Azure.Cosmos.Client", "Microsoft.Azure.Cosmos.CosmosClient", "GetDatabaseQueryStreamIterator",  new[] { "Microsoft.Azure.Cosmos.FeedIterator`1<T>", "System.String", "System.String", "Microsoft.Azure.Cosmos.QueryRequestOptions" }, 3, 6, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.CosmosDb.ClientQueryIteratorsIntegrations"));
            definitionList.Add(new("Microsoft.Azure.Cosmos.Client", "Microsoft.Azure.Cosmos.DatabaseCore", "GetContainerQueryIterator",  new[] { "Microsoft.Azure.Cosmos.FeedIterator`1<T>", "Microsoft.Azure.Cosmos.QueryDefinition", "System.String", "Microsoft.Azure.Cosmos.QueryRequestOptions" }, 3, 6, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.CosmosDb.DatabaseQueryIteratorsIntegrations"));
            definitionList.Add(new("Microsoft.Azure.Cosmos.Client", "Microsoft.Azure.Cosmos.DatabaseCore", "GetContainerQueryIterator",  new[] { "Microsoft.Azure.Cosmos.FeedIterator`1<T>", "System.String", "System.String", "Microsoft.Azure.Cosmos.QueryRequestOptions" }, 3, 6, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.CosmosDb.DatabaseQueryIteratorsIntegrations"));
            definitionList.Add(new("Microsoft.Azure.Cosmos.Client", "Microsoft.Azure.Cosmos.DatabaseCore", "GetContainerQueryStreamIterator",  new[] { "Microsoft.Azure.Cosmos.FeedIterator`1<T>", "Microsoft.Azure.Cosmos.QueryDefinition", "System.String", "Microsoft.Azure.Cosmos.QueryRequestOptions" }, 3, 6, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.CosmosDb.DatabaseQueryIteratorsIntegrations"));
            definitionList.Add(new("Microsoft.Azure.Cosmos.Client", "Microsoft.Azure.Cosmos.DatabaseCore", "GetContainerQueryStreamIterator",  new[] { "Microsoft.Azure.Cosmos.FeedIterator`1<T>", "System.String", "System.String", "Microsoft.Azure.Cosmos.QueryRequestOptions" }, 3, 6, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.CosmosDb.DatabaseQueryIteratorsIntegrations"));
            definitionList.Add(new("Microsoft.Azure.Cosmos.Client", "Microsoft.Azure.Cosmos.DatabaseCore", "GetUserQueryIterator",  new[] { "Microsoft.Azure.Cosmos.FeedIterator`1<T>", "Microsoft.Azure.Cosmos.QueryDefinition", "System.String", "Microsoft.Azure.Cosmos.QueryRequestOptions" }, 3, 6, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.CosmosDb.DatabaseQueryIteratorsIntegrations"));
            definitionList.Add(new("Microsoft.Azure.Cosmos.Client", "Microsoft.Azure.Cosmos.DatabaseCore", "GetUserQueryIterator",  new[] { "Microsoft.Azure.Cosmos.FeedIterator`1<T>", "System.String", "System.String", "Microsoft.Azure.Cosmos.QueryRequestOptions" }, 3, 6, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.CosmosDb.DatabaseQueryIteratorsIntegrations"));

            // Couchbase
            definitionList.Add(new("Couchbase.NetClient", "Couchbase.Core.ClusterNode", "ExecuteOp",  new[] { "System.Threading.Tasks.Task", "Couchbase.Core.IO.Operations.IOperation", "Couchbase.Core.IO.Operations.CancellationTokenPair" }, 3, 1, 3, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Couchbase.ClusterNodeIntegration"));
            definitionList.Add(new("Couchbase.NetClient", "Couchbase.Core.ClusterNode", "ExecuteOp",  new[] { "System.Threading.Tasks.Task", "Couchbase.Core.IO.Operations.IOperation", "System.Threading.CancellationToken" }, 3, 0, 7, 3, 1, 2, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Couchbase.ClusterNodeIntegration"));
            definitionList.Add(new("Couchbase.NetClient", "Couchbase.Core.ClusterNode", "ExecuteOp",  new[] { "System.Threading.Tasks.Task", "Couchbase.Core.IO.Connections.IConnection", "Couchbase.Core.IO.Operations.IOperation", "Couchbase.Core.IO.Operations.CancellationTokenPair" }, 3, 1, 3, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Couchbase.ClusterNodeIntegrationBis"));
            definitionList.Add(new("Couchbase.NetClient", "Couchbase.Core.ClusterNode", "ExecuteOp",  new[] { "System.Threading.Tasks.Task", "Couchbase.Core.IO.Connections.IConnection", "Couchbase.Core.IO.Operations.IOperation", "System.Threading.CancellationToken" }, 3, 0, 0, 3, 1, 1, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Couchbase.ClusterNodeIntegrationBis"));
            definitionList.Add(new("Couchbase.NetClient", "Couchbase.Core.ClusterNode", "ExecuteOp",  new[] { "System.Threading.Tasks.Task", "Couchbase.Core.IO.Operations.IOperation", "System.Threading.CancellationToken", "System.TimeSpan" }, 3, 0, 0, 3, 1, 2, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Couchbase.ClusterNodeIntegrationTer"));
            definitionList.Add(new("Couchbase.NetClient", "Couchbase.Core.ClusterNode", "SendAsync",  new[] { "System.Threading.Tasks.Task", "Couchbase.Core.IO.Operations.IOperation", "Couchbase.Core.IO.Operations.CancellationTokenPair" }, 3, 1, 3, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Couchbase.ClusterNodeIntegration"));
            definitionList.Add(new("Couchbase.NetClient", "Couchbase.Core.ClusterNode", "SendAsync",  new[] { "System.Threading.Tasks.Task", "Couchbase.Core.IO.Operations.IOperation", "System.Threading.CancellationToken" }, 3, 0, 7, 3, 1, 2, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Couchbase.ClusterNodeIntegration"));
            definitionList.Add(new("Couchbase.NetClient", "Couchbase.Core.ClusterNode", "SendAsync",  new[] { "System.Threading.Tasks.Task", "Couchbase.Core.IO.Operations.IOperation", "System.Threading.CancellationToken", "System.TimeSpan" }, 3, 0, 0, 3, 1, 2, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Couchbase.ClusterNodeIntegrationTer"));
            definitionList.Add(new("Couchbase.NetClient", "Couchbase.IO.Services.MultiplexingIOService", "Execute",  new[] { "Couchbase.IOperationResult<T>", "Couchbase.IO.Operations.IOperation" }, 2, 2, 8, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Couchbase.IIOServiceExecuteIntegration"));
            definitionList.Add(new("Couchbase.NetClient", "Couchbase.IO.Services.MultiplexingIOService", "Execute",  new[] { "Couchbase.IOperationResult<T>", "Couchbase.IO.Operations.IOperation`1[!!0]" }, 2, 2, 8, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Couchbase.IIOServiceExecuteIntegration"));
            definitionList.Add(new("Couchbase.NetClient", "Couchbase.IO.Services.MultiplexingIOService", "Execute",  new[] { "Couchbase.IOperationResult<T>", "Couchbase.IO.Operations.IOperation`1[!!0]", "Couchbase.IO.IConnection" }, 2, 2, 8, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Couchbase.IIOServiceExecuteIntegrationBis"));
            definitionList.Add(new("Couchbase.NetClient", "Couchbase.IO.Services.MultiplexingIOService", "ExecuteAsync",  new[] { "System.Threading.Tasks.Task", "Couchbase.IO.Operations.IOperation" }, 2, 2, 8, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Couchbase.IIOServiceExecuteAsyncIntegration"));
            definitionList.Add(new("Couchbase.NetClient", "Couchbase.IO.Services.MultiplexingIOService", "ExecuteAsync",  new[] { "System.Threading.Tasks.Task", "Couchbase.IO.Operations.IOperation`1[!!0]" }, 2, 2, 8, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Couchbase.IIOServiceExecuteAsyncIntegration"));
            definitionList.Add(new("Couchbase.NetClient", "Couchbase.IO.Services.MultiplexingIOService", "ExecuteAsync",  new[] { "System.Threading.Tasks.Task", "Couchbase.IO.Operations.IOperation`1[!!0]", "Couchbase.IO.IConnection" }, 2, 2, 8, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Couchbase.IIOServiceExecuteAsyncIntegrationBis"));
            definitionList.Add(new("Couchbase.NetClient", "Couchbase.IO.Services.PooledIOService", "Execute",  new[] { "Couchbase.IOperationResult<T>", "Couchbase.IO.Operations.IOperation" }, 2, 2, 8, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Couchbase.IIOServiceExecuteIntegration"));
            definitionList.Add(new("Couchbase.NetClient", "Couchbase.IO.Services.PooledIOService", "Execute",  new[] { "Couchbase.IOperationResult<T>", "Couchbase.IO.Operations.IOperation`1[!!0]" }, 2, 2, 8, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Couchbase.IIOServiceExecuteIntegration"));
            definitionList.Add(new("Couchbase.NetClient", "Couchbase.IO.Services.PooledIOService", "Execute",  new[] { "Couchbase.IOperationResult<T>", "Couchbase.IO.Operations.IOperation`1[!!0]", "Couchbase.IO.IConnection" }, 2, 2, 8, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Couchbase.IIOServiceExecuteIntegrationBis"));
            definitionList.Add(new("Couchbase.NetClient", "Couchbase.IO.Services.PooledIOService", "ExecuteAsync",  new[] { "System.Threading.Tasks.Task", "Couchbase.IO.Operations.IOperation" }, 2, 2, 8, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Couchbase.IIOServiceExecuteAsyncIntegration"));
            definitionList.Add(new("Couchbase.NetClient", "Couchbase.IO.Services.PooledIOService", "ExecuteAsync",  new[] { "System.Threading.Tasks.Task", "Couchbase.IO.Operations.IOperation`1[!!0]" }, 2, 2, 8, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Couchbase.IIOServiceExecuteAsyncIntegration"));
            definitionList.Add(new("Couchbase.NetClient", "Couchbase.IO.Services.PooledIOService", "ExecuteAsync",  new[] { "System.Threading.Tasks.Task", "Couchbase.IO.Operations.IOperation`1[!!0]", "Couchbase.IO.IConnection" }, 2, 2, 8, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Couchbase.IIOServiceExecuteAsyncIntegrationBis"));
            definitionList.Add(new("Couchbase.NetClient", "Couchbase.IO.Services.SharedPooledIOService", "Execute",  new[] { "Couchbase.IOperationResult<T>", "Couchbase.IO.Operations.IOperation" }, 2, 2, 8, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Couchbase.IIOServiceExecuteIntegration"));
            definitionList.Add(new("Couchbase.NetClient", "Couchbase.IO.Services.SharedPooledIOService", "Execute",  new[] { "Couchbase.IOperationResult<T>", "Couchbase.IO.Operations.IOperation`1[!!0]" }, 2, 2, 8, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Couchbase.IIOServiceExecuteIntegration"));
            definitionList.Add(new("Couchbase.NetClient", "Couchbase.IO.Services.SharedPooledIOService", "Execute",  new[] { "Couchbase.IOperationResult<T>", "Couchbase.IO.Operations.IOperation`1[!!0]", "Couchbase.IO.IConnection" }, 2, 2, 8, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Couchbase.IIOServiceExecuteIntegrationBis"));
            definitionList.Add(new("Couchbase.NetClient", "Couchbase.IO.Services.SharedPooledIOService", "ExecuteAsync",  new[] { "System.Threading.Tasks.Task", "Couchbase.IO.Operations.IOperation" }, 2, 2, 8, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Couchbase.IIOServiceExecuteAsyncIntegration"));
            definitionList.Add(new("Couchbase.NetClient", "Couchbase.IO.Services.SharedPooledIOService", "ExecuteAsync",  new[] { "System.Threading.Tasks.Task", "Couchbase.IO.Operations.IOperation`1[!!0]" }, 2, 2, 8, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Couchbase.IIOServiceExecuteAsyncIntegration"));
            definitionList.Add(new("Couchbase.NetClient", "Couchbase.IO.Services.SharedPooledIOService", "ExecuteAsync",  new[] { "System.Threading.Tasks.Task", "Couchbase.IO.Operations.IOperation`1[!!0]", "Couchbase.IO.IConnection" }, 2, 2, 8, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Couchbase.IIOServiceExecuteAsyncIntegrationBis"));

            // ElasticsearchNet
            definitionList.Add(new("Elasticsearch.Net", "Elasticsearch.Net.RequestPipeline", "CallElasticsearch",  new[] { "T", "Elasticsearch.Net.RequestData" }, 6, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Elasticsearch.V6.RequestPipeline_CallElasticsearch_Integration"));
            definitionList.Add(new("Elasticsearch.Net", "Elasticsearch.Net.RequestPipeline", "CallElasticsearch",  new[] { "Elasticsearch.Net.ElasticsearchResponse`1<T>", "Elasticsearch.Net.RequestData" }, 5, 0, 0, 5, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Elasticsearch.V5.RequestPipeline_CallElasticsearch_Integration"));
            definitionList.Add(new("Elasticsearch.Net", "Elasticsearch.Net.RequestPipeline", "CallElasticsearchAsync",  new[] { "System.Threading.Tasks.Task`1<T>", "Elasticsearch.Net.RequestData", "System.Threading.CancellationToken" }, 6, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Elasticsearch.V6.RequestPipeline_CallElasticsearchAsync_Integration"));
            definitionList.Add(new("Elasticsearch.Net", "Elasticsearch.Net.RequestPipeline", "CallElasticsearchAsync",  new[] { "System.Threading.Tasks.Task`1<Elasticsearch.Net.ElasticsearchResponse`1<T>>", "Elasticsearch.Net.RequestData", "System.Threading.CancellationToken" }, 5, 0, 0, 5, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Elasticsearch.V5.RequestPipeline_CallElasticsearchAsync_Integration"));
            definitionList.Add(new("Elasticsearch.Net", "Elasticsearch.Net.Transport`1", "Request",  new[] { "T", "Elasticsearch.Net.HttpMethod", "System.String", "Elasticsearch.Net.PostData", "Elasticsearch.Net.IRequestParameters" }, 7, 0, 0, 7, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Elasticsearch.V7.Transport_Request_Integration"));
            definitionList.Add(new("Elasticsearch.Net", "Elasticsearch.Net.Transport`1", "RequestAsync",  new[] { "System.Threading.Tasks.Task`1<T>", "Elasticsearch.Net.HttpMethod", "System.String", "System.Threading.CancellationToken", "Elasticsearch.Net.PostData", "Elasticsearch.Net.IRequestParameters" }, 7, 0, 0, 7, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Elasticsearch.V7.Transport_RequestAsync_Integration"));

            // GraphQL
            definitionList.Add(new("GraphQL", "GraphQL.Execution.ExecutionStrategy", "ExecuteAsync",  new[] { "System.Threading.Tasks.Task`1<GraphQL.ExecutionResult>", "GraphQL.Execution.ExecutionContext" }, 2, 3, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.GraphQL.ExecuteAsyncIntegration"));
            definitionList.Add(new("GraphQL", "GraphQL.Execution.SubscriptionExecutionStrategy", "ExecuteAsync",  new[] { "System.Threading.Tasks.Task`1<GraphQL.ExecutionResult>", "GraphQL.Execution.ExecutionContext" }, 2, 3, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.GraphQL.ExecuteAsyncIntegration"));
            definitionList.Add(new("GraphQL", "GraphQL.Validation.DocumentValidator", "Validate",  new[] { "GraphQL.Validation.IValidationResult", "System.String", "GraphQL.Types.ISchema", "GraphQL.Language.AST.Document", "System.Collections.Generic.IEnumerable`1[GraphQL.Validation.IValidationRule]", "_", "GraphQL.Inputs" }, 2, 3, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.GraphQL.ValidateIntegration"));
            definitionList.Add(new("GraphQL", "GraphQL.Validation.DocumentValidator", "ValidateAsync",  new[] { "System.Threading.Tasks.Task`1<T>", "GraphQL.Types.ISchema", "GraphQL.Language.AST.Document", "GraphQL.Language.AST.VariableDefinitions", "System.Collections.Generic.IEnumerable`1[GraphQL.Validation.IValidationRule]", "_", "GraphQL.Inputs" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.GraphQL.ValidateAsync4Integration"));
            definitionList.Add(new("GraphQL", "GraphQL.Validation.DocumentValidator", "ValidateAsync",  new[] { "System.Threading.Tasks.Task`1<T>", "System.String", "GraphQL.Types.ISchema", "GraphQL.Language.AST.Document", "System.Collections.Generic.IEnumerable`1[GraphQL.Validation.IValidationRule]", "_", "GraphQL.Inputs" }, 3, 0, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.GraphQL.ValidateAsyncIntegration"));
            definitionList.Add(new("GraphQL.SystemReactive", "GraphQL.Execution.SubscriptionExecutionStrategy", "ExecuteAsync",  new[] { "System.Threading.Tasks.Task`1<GraphQL.ExecutionResult>", "GraphQL.Execution.ExecutionContext" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.GraphQL.ExecuteAsyncIntegration"));

            // HttpMessageHandler
            definitionList.Add(new("System.Net.Http", "System.Net.Http.CurlHandler", "SendAsync",  new[] { "System.Threading.Tasks.Task`1<System.Net.Http.HttpResponseMessage>", "System.Net.Http.HttpRequestMessage", "System.Threading.CancellationToken" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Http.HttpClient.CurlHandler.CurlHandlerIntegration"));
            definitionList.Add(new("System.Net.Http", "System.Net.Http.HttpClientHandler", "Send",  new[] { "System.Net.Http.HttpResponseMessage", "System.Net.Http.HttpRequestMessage", "System.Threading.CancellationToken" }, 5, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Http.HttpClient.HttpClientHandler.HttpClientHandlerSyncIntegration"));
            definitionList.Add(new("System.Net.Http", "System.Net.Http.HttpClientHandler", "SendAsync",  new[] { "System.Threading.Tasks.Task`1<System.Net.Http.HttpResponseMessage>", "System.Net.Http.HttpRequestMessage", "System.Threading.CancellationToken" }, 4, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Http.HttpClient.HttpClientHandler.HttpClientHandlerIntegration"));
            definitionList.Add(new("System.Net.Http", "System.Net.Http.SocketsHttpHandler", "Send",  new[] { "System.Net.Http.HttpResponseMessage", "System.Net.Http.HttpRequestMessage", "System.Threading.CancellationToken" }, 5, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Http.HttpClient.SocketsHttpHandler.SocketsHttpHandlerSyncIntegration"));
            definitionList.Add(new("System.Net.Http", "System.Net.Http.SocketsHttpHandler", "SendAsync",  new[] { "System.Threading.Tasks.Task`1<System.Net.Http.HttpResponseMessage>", "System.Net.Http.HttpRequestMessage", "System.Threading.CancellationToken" }, 4, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Http.HttpClient.SocketsHttpHandler.SocketsHttpHandlerIntegration"));
            definitionList.Add(new("System.Net.Http", "System.Net.Http.WinHttpHandler", "SendAsync",  new[] { "System.Threading.Tasks.Task`1<System.Net.Http.HttpResponseMessage>", "System.Net.Http.HttpRequestMessage", "System.Threading.CancellationToken" }, 4, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Http.HttpClient.WinHttpHandler.WinHttpHandlerIntegration"));
            definitionList.Add(new("System.Net.Http.WinHttpHandler", "System.Net.Http.WinHttpHandler", "SendAsync",  new[] { "System.Threading.Tasks.Task`1<System.Net.Http.HttpResponseMessage>", "System.Net.Http.HttpRequestMessage", "System.Threading.CancellationToken" }, 4, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Http.HttpClient.WinHttpHandler.WinHttpHandlerIntegration"));

            // ILogger
            definitionList.Add(new("Microsoft.Extensions.Logging", "Microsoft.Extensions.Logging.LoggerFactoryScopeProvider", "ForEachScope",  new[] { "System.Void", "System.Action`2[System.Object,!!0]", "!!0" }, 2, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Logging.ILogger.LoggerFactoryScopeProviderForEachScopeIntegration"));
            definitionList.Add(new("Microsoft.Extensions.Logging.Abstractions", "Microsoft.Extensions.Logging.LoggerExternalScopeProvider", "ForEachScope",  new[] { "System.Void", "System.Action`2[System.Object,!!0]", "!!0" }, 2, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Logging.ILogger.LoggerExternalScopeProviderForEachScopeIntegration"));

            // Kafka
            definitionList.Add(new("Confluent.Kafka", "Confluent.Kafka.Consumer`2", "Close",  new[] { "System.Void" }, 1, 4, 0, 1, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Kafka.KafkaConsumerCloseIntegration"));
            definitionList.Add(new("Confluent.Kafka", "Confluent.Kafka.Consumer`2", "Consume",  new[] { "Confluent.Kafka.ConsumeResult`2[!0,!1]", "System.Int32" }, 1, 4, 0, 1, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Kafka.KafkaConsumerConsumeIntegration"));
            definitionList.Add(new("Confluent.Kafka", "Confluent.Kafka.Consumer`2", "Dispose",  new[] { "System.Void" }, 1, 4, 0, 1, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Kafka.KafkaConsumerDisposeIntegration"));
            definitionList.Add(new("Confluent.Kafka", "Confluent.Kafka.Consumer`2", "Unsubscribe",  new[] { "System.Void" }, 1, 4, 0, 1, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Kafka.KafkaConsumerUnsubscribeIntegration"));
            definitionList.Add(new("Confluent.Kafka", "Confluent.Kafka.Producer`2", "Produce",  new[] { "System.Void", "Confluent.Kafka.TopicPartition", "Confluent.Kafka.Message`2[!0,!1]", "System.Action`1[Confluent.Kafka.DeliveryReport`2[!0,!1]]" }, 1, 4, 0, 1, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Kafka.KafkaProduceSyncIntegration"));
            definitionList.Add(new("Confluent.Kafka", "Confluent.Kafka.Producer`2", "ProduceAsync",  new[] { "System.Threading.Tasks.Task`1[Confluent.Kafka.DeliveryReport`2[!0,!1]]", "Confluent.Kafka.TopicPartition", "Confluent.Kafka.Message`2[!0,!1]", "System.Threading.CancellationToken" }, 1, 4, 0, 1, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Kafka.KafkaProduceAsyncIntegration"));
            definitionList.Add(new("Confluent.Kafka", "Confluent.Kafka.Producer`2+TypedDeliveryHandlerShim_Action", ".ctor",  new[] { "System.Void", "System.String", "!0", "!1", "System.Action`1[Confluent.Kafka.DeliveryReport`2[!0,!1]]" }, 1, 4, 0, 1, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Kafka.KafkaProduceSyncDeliveryHandlerIntegration"));

            // Log4Net
            definitionList.Add(new("log4net", "log4net.Util.AppenderAttachedImpl", "AppendLoopOnAppenders",  new[] { "System.Int32", "log4net.Core.LoggingEvent" }, 1, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Log4Net.AppenderAttachedImplIntegration"));

            // MongoDb
            definitionList.Add(new("MongoDB.Driver.Core", "MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1", "Execute",  new[] { "T", "MongoDB.Driver.Core.Connections.IConnection", "System.Threading.CancellationToken" }, 2, 2, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.MongoDb.IWireProtocol_Generic_Execute_Integration"));
            definitionList.Add(new("MongoDB.Driver.Core", "MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1", "ExecuteAsync",  new[] { "System.Threading.Tasks.Task`1<T>", "MongoDB.Driver.Core.Connections.IConnection", "System.Threading.CancellationToken" }, 2, 1, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.MongoDb.IWireProtocol_ExecuteAsync_Integration"));
            definitionList.Add(new("MongoDB.Driver.Core", "MongoDB.Driver.Core.WireProtocol.CommandUsingQueryMessageWireProtocol`1", "Execute",  new[] { "T", "MongoDB.Driver.Core.Connections.IConnection", "System.Threading.CancellationToken" }, 2, 2, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.MongoDb.IWireProtocol_Generic_Execute_Integration"));
            definitionList.Add(new("MongoDB.Driver.Core", "MongoDB.Driver.Core.WireProtocol.CommandUsingQueryMessageWireProtocol`1", "ExecuteAsync",  new[] { "System.Threading.Tasks.Task`1<T>", "MongoDB.Driver.Core.Connections.IConnection", "System.Threading.CancellationToken" }, 2, 1, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.MongoDb.IWireProtocol_ExecuteAsync_Integration"));
            definitionList.Add(new("MongoDB.Driver.Core", "MongoDB.Driver.Core.WireProtocol.CommandWireProtocol`1", "Execute",  new[] { "T", "MongoDB.Driver.Core.Connections.IConnection", "System.Threading.CancellationToken" }, 2, 2, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.MongoDb.IWireProtocol_Generic_Execute_Integration"));
            definitionList.Add(new("MongoDB.Driver.Core", "MongoDB.Driver.Core.WireProtocol.CommandWireProtocol`1", "ExecuteAsync",  new[] { "System.Threading.Tasks.Task`1<T>", "MongoDB.Driver.Core.Connections.IConnection", "System.Threading.CancellationToken" }, 2, 1, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.MongoDb.IWireProtocol_ExecuteAsync_Integration"));
            definitionList.Add(new("MongoDB.Driver.Core", "MongoDB.Driver.Core.WireProtocol.GetMoreWireProtocol`1", "Execute",  new[] { "T", "MongoDB.Driver.Core.Connections.IConnection", "System.Threading.CancellationToken" }, 2, 2, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.MongoDb.IWireProtocol_Generic_Execute_Integration"));
            definitionList.Add(new("MongoDB.Driver.Core", "MongoDB.Driver.Core.WireProtocol.GetMoreWireProtocol`1", "ExecuteAsync",  new[] { "System.Threading.Tasks.Task`1<T>", "MongoDB.Driver.Core.Connections.IConnection", "System.Threading.CancellationToken" }, 2, 1, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.MongoDb.IWireProtocol_ExecuteAsync_Integration"));
            definitionList.Add(new("MongoDB.Driver.Core", "MongoDB.Driver.Core.WireProtocol.KillCursorsWireProtocol", "Execute",  new[] { "System.Void", "MongoDB.Driver.Core.Connections.IConnection", "System.Threading.CancellationToken" }, 2, 2, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.MongoDb.IWireProtocol_Execute_Integration"));
            definitionList.Add(new("MongoDB.Driver.Core", "MongoDB.Driver.Core.WireProtocol.KillCursorsWireProtocol", "ExecuteAsync",  new[] { "System.Threading.Tasks.Task", "MongoDB.Driver.Core.Connections.IConnection", "System.Threading.CancellationToken" }, 2, 1, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.MongoDb.IWireProtocol_ExecuteAsync_Integration"));
            definitionList.Add(new("MongoDB.Driver.Core", "MongoDB.Driver.Core.WireProtocol.QueryWireProtocol`1", "Execute",  new[] { "T", "MongoDB.Driver.Core.Connections.IConnection", "System.Threading.CancellationToken" }, 2, 2, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.MongoDb.IWireProtocol_Generic_Execute_Integration"));
            definitionList.Add(new("MongoDB.Driver.Core", "MongoDB.Driver.Core.WireProtocol.QueryWireProtocol`1", "ExecuteAsync",  new[] { "System.Threading.Tasks.Task`1<T>", "MongoDB.Driver.Core.Connections.IConnection", "System.Threading.CancellationToken" }, 2, 1, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.MongoDb.IWireProtocol_ExecuteAsync_Integration"));
            definitionList.Add(new("MongoDB.Driver.Core", "MongoDB.Driver.Core.WireProtocol.WriteWireProtocolBase`1", "Execute",  new[] { "T", "MongoDB.Driver.Core.Connections.IConnection", "System.Threading.CancellationToken" }, 2, 2, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.MongoDb.IWireProtocol_Generic_Execute_Integration"));
            definitionList.Add(new("MongoDB.Driver.Core", "MongoDB.Driver.Core.WireProtocol.WriteWireProtocolBase`1", "ExecuteAsync",  new[] { "System.Threading.Tasks.Task`1<T>", "MongoDB.Driver.Core.Connections.IConnection", "System.Threading.CancellationToken" }, 2, 1, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.MongoDb.IWireProtocol_ExecuteAsync_Integration"));

            // Msmq
            definitionList.Add(new("System.Messaging", "System.Messaging.MessageQueue", "Purge",  new[] { "System.Void" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Msmq.MessageQueue_Purge_Integration"));
            definitionList.Add(new("System.Messaging", "System.Messaging.MessageQueue", "ReceiveCurrent",  new[] { "System.Messaging.Message", "System.TimeSpan", "System.Int32", "System.Messaging.Interop.CursorHandle", "System.Messaging.MessagePropertyFilter", "System.Messaging.MessageQueueTransaction", "System.Messaging.MessageQueueTransactionType" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Msmq.MessageQueue_ReceiveCurrent_Integration"));
            definitionList.Add(new("System.Messaging", "System.Messaging.MessageQueue", "SendInternal",  new[] { "System.Void", "System.Object", "System.Messaging.MessageQueueTransaction", "System.Messaging.MessageQueueTransactionType" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Msmq.MessageQueue_SendInternal_Integration"));

            // MsTestV2
            definitionList.Add(new("Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter", "Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestMethodRunner", "Execute",  new[] { "Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.ObjectModel.UnitTestResult[]" }, 14, 0, 0, 14, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Testing.MsTestV2.TestMethodRunnerExecuteIntegration"));
            definitionList.Add(new("Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter", "Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.UnitTestRunner", "IsTestMethodRunnable",  new[] { "System.Boolean", "Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.ObjectModel.TestMethod", "Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestMethodInfo", "Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.ObjectModel.UnitTestResult[]&" }, 14, 0, 0, 14, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Testing.MsTestV2.UnitTestRunnerIsTestMethodRunnableIntegration"));
            definitionList.Add(new("Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter", "Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.UnitTestRunner", "RunCleanup",  new[] { "Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.RunCleanupResult" }, 14, 0, 0, 14, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Testing.MsTestV2.UnitTestRunnerRunCleanupIntegration"));
            definitionList.Add(new("Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter", "Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.UnitTestRunner", "RunSingleTest",  new[] { "Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.ObjectModel.UnitTestResult[]", "Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.ObjectModel.TestMethod", "System.Collections.Generic.IDictionary`2[System.String,System.Object]" }, 14, 0, 0, 14, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Testing.MsTestV2.UnitTestRunnerRunSingleTestIntegration"));
            definitionList.Add(new("Microsoft.VisualStudio.TestPlatform.TestFramework", "Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute", "Execute",  new[] { "Microsoft.VisualStudio.TestTools.UnitTesting.TestResult", "Microsoft.VisualStudio.TestTools.UnitTesting.ITestMethod" }, 14, 0, 0, 14, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Testing.MsTestV2.TestMethodAttributeExecuteIntegration"));

            // MySql
            definitionList.Add(new("MySql.Data", "MySql.Data.MySqlClient.MySqlCommand", "ExecuteDbDataReader",  new[] { "System.Data.Common.DbDataReader", "System.Data.CommandBehavior" }, 6, 7, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorIntegration"));
            definitionList.Add(new("MySql.Data", "MySql.Data.MySqlClient.MySqlCommand", "ExecuteDbDataReader",  new[] { "System.Data.Common.DbDataReader", "System.Data.CommandBehavior" }, 8, 0, 0, 8, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorIntegration"));
            definitionList.Add(new("MySql.Data", "MySql.Data.MySqlClient.MySqlCommand", "ExecuteNonQuery",  new[] { "System.Int32" }, 6, 7, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteNonQueryIntegration"));
            definitionList.Add(new("MySql.Data", "MySql.Data.MySqlClient.MySqlCommand", "ExecuteNonQuery",  new[] { "System.Int32" }, 8, 0, 0, 8, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteNonQueryIntegration"));
            definitionList.Add(new("MySql.Data", "MySql.Data.MySqlClient.MySqlCommand", "ExecuteReader",  new[] { "MySql.Data.MySqlClient.MySqlDataReader" }, 6, 7, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderIntegration"));
            definitionList.Add(new("MySql.Data", "MySql.Data.MySqlClient.MySqlCommand", "ExecuteReader",  new[] { "MySql.Data.MySqlClient.MySqlDataReader" }, 8, 0, 0, 8, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderIntegration"));
            definitionList.Add(new("MySql.Data", "MySql.Data.MySqlClient.MySqlCommand", "ExecuteReader",  new[] { "MySql.Data.MySqlClient.MySqlDataReader", "System.Data.CommandBehavior" }, 6, 7, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorIntegration"));
            definitionList.Add(new("MySql.Data", "MySql.Data.MySqlClient.MySqlCommand", "ExecuteReader",  new[] { "MySql.Data.MySqlClient.MySqlDataReader", "System.Data.CommandBehavior" }, 8, 0, 0, 8, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorIntegration"));
            definitionList.Add(new("MySql.Data", "MySql.Data.MySqlClient.MySqlCommand", "ExecuteScalar",  new[] { "System.Object" }, 6, 7, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteScalarIntegration"));
            definitionList.Add(new("MySql.Data", "MySql.Data.MySqlClient.MySqlCommand", "ExecuteScalar",  new[] { "System.Object" }, 8, 0, 0, 8, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteScalarIntegration"));
            definitionList.Add(new("MySqlConnector", "MySqlConnector.MySqlCommand", "ExecuteDbDataReader",  new[] { "System.Data.Common.DbDataReader", "System.Data.CommandBehavior" }, 1, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorIntegration"));
            definitionList.Add(new("MySqlConnector", "MySqlConnector.MySqlCommand", "ExecuteDbDataReaderAsync",  new[] { "System.Threading.Tasks.Task`1<System.Data.Common.DbDataReader>", "System.Data.CommandBehavior", "System.Threading.CancellationToken" }, 1, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorAndCancellationAsyncIntegration"));
            definitionList.Add(new("MySqlConnector", "MySqlConnector.MySqlCommand", "ExecuteNonQuery",  new[] { "System.Int32" }, 1, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteNonQueryIntegration"));
            definitionList.Add(new("MySqlConnector", "MySqlConnector.MySqlCommand", "ExecuteNonQueryAsync",  new[] { "System.Threading.Tasks.Task`1<System.Int32>", "System.Threading.CancellationToken" }, 1, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteNonQueryAsyncIntegration"));
            definitionList.Add(new("MySqlConnector", "MySqlConnector.MySqlCommand", "ExecuteReader",  new[] { "MySqlConnector.MySqlDataReader" }, 1, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderIntegration"));
            definitionList.Add(new("MySqlConnector", "MySqlConnector.MySqlCommand", "ExecuteReader",  new[] { "MySqlConnector.MySqlDataReader", "System.Data.CommandBehavior" }, 1, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorIntegration"));
            definitionList.Add(new("MySqlConnector", "MySqlConnector.MySqlCommand", "ExecuteReaderAsync",  new[] { "System.Threading.Tasks.Task`1<MySqlConnector.MySqlDataReader>", "System.Threading.CancellationToken" }, 1, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithCancellationAsyncIntegration"));
            definitionList.Add(new("MySqlConnector", "MySqlConnector.MySqlCommand", "ExecuteReaderAsync",  new[] { "System.Threading.Tasks.Task`1<MySqlConnector.MySqlDataReader>", "System.Data.CommandBehavior", "System.Threading.CancellationToken" }, 1, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorAndCancellationAsyncIntegration"));
            definitionList.Add(new("MySqlConnector", "MySqlConnector.MySqlCommand", "ExecuteScalar",  new[] { "System.Object" }, 1, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteScalarIntegration"));
            definitionList.Add(new("MySqlConnector", "MySqlConnector.MySqlCommand", "ExecuteScalarAsync",  new[] { "System.Threading.Tasks.Task`1<System.Object>", "System.Threading.CancellationToken" }, 1, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteScalarAsyncIntegration"));

            // NLog
            definitionList.Add(new("NLog", "NLog.LoggerImpl", "Write",  new[] { "System.Void", "System.Type", "NLog.Internal.TargetWithFilterChain", "NLog.LogEventInfo", "NLog.LogFactory" }, 1, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Logging.NLog.LogsInjection.LoggerImplWriteIntegration"));

            // Npgsql
            definitionList.Add(new("Npgsql", "Npgsql.NpgsqlCommand", "ExecuteDbDataReader",  new[] { "System.Data.Common.DbDataReader", "System.Data.CommandBehavior" }, 4, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorIntegration"));
            definitionList.Add(new("Npgsql", "Npgsql.NpgsqlCommand", "ExecuteDbDataReaderAsync",  new[] { "System.Threading.Tasks.Task`1<System.Data.Common.DbDataReader>", "System.Data.CommandBehavior", "System.Threading.CancellationToken" }, 4, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorAndCancellationAsyncIntegration"));
            definitionList.Add(new("Npgsql", "Npgsql.NpgsqlCommand", "ExecuteNonQuery",  new[] { "System.Int32" }, 4, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteNonQueryIntegration"));
            definitionList.Add(new("Npgsql", "Npgsql.NpgsqlCommand", "ExecuteNonQueryAsync",  new[] { "System.Threading.Tasks.Task`1<System.Int32>", "System.Threading.CancellationToken" }, 4, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteNonQueryAsyncIntegration"));
            definitionList.Add(new("Npgsql", "Npgsql.NpgsqlCommand", "ExecuteReader",  new[] { "Npgsql.NpgsqlDataReader" }, 4, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderIntegration"));
            definitionList.Add(new("Npgsql", "Npgsql.NpgsqlCommand", "ExecuteReader",  new[] { "Npgsql.NpgsqlDataReader", "System.Data.CommandBehavior" }, 4, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorIntegration"));
            definitionList.Add(new("Npgsql", "Npgsql.NpgsqlCommand", "ExecuteReaderAsync",  new[] { "System.Threading.Tasks.Task`1<Npgsql.NpgsqlDataReader>", "System.Data.CommandBehavior", "System.Threading.CancellationToken" }, 4, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorAndCancellationAsyncIntegration"));
            definitionList.Add(new("Npgsql", "Npgsql.NpgsqlCommand", "ExecuteScalar",  new[] { "System.Object" }, 4, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteScalarIntegration"));
            definitionList.Add(new("Npgsql", "Npgsql.NpgsqlCommand", "ExecuteScalarAsync",  new[] { "System.Threading.Tasks.Task`1<System.Object>", "System.Threading.CancellationToken" }, 4, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteScalarAsyncIntegration"));

            // NUnit
            definitionList.Add(new("nunit.framework", "NUnit.Framework.Api.NUnitTestAssemblyRunner", "WaitForCompletion",  new[] { "System.Boolean", "System.Int32" }, 3, 0, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Testing.NUnit.NUnitTestAssemblyRunnerWaitForCompletionIntegration"));
            definitionList.Add(new("nunit.framework", "NUnit.Framework.Internal.Commands.SkipCommand", "Execute",  new[] { "NUnit.Framework.Internal.TestResult", "NUnit.Framework.Internal.TestExecutionContext" }, 3, 0, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Testing.NUnit.NUnitSkipCommandExecuteIntegration"));
            definitionList.Add(new("nunit.framework", "NUnit.Framework.Internal.Commands.TestMethodCommand", "Execute",  new[] { "NUnit.Framework.Internal.TestResult", "NUnit.Framework.Internal.TestExecutionContext" }, 3, 0, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Testing.NUnit.NUnitTestMethodCommandExecuteIntegration"));
            definitionList.Add(new("nunit.framework", "NUnit.Framework.Internal.Execution.CompositeWorkItem", "SkipChildren",  new[] { "System.Void", "_", "NUnit.Framework.Interfaces.ResultState", "System.String" }, 3, 0, 0, 3, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Testing.NUnit.NUnitCompositeWorkItemSkipChildrenIntegration"));
            definitionList.Add(new("NUnit3.TestAdapter", "NUnit.VisualStudio.TestAdapter.NUnitTestAdapter", "Unload",  new[] { "System.Void" }, 3, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Testing.NUnit.NUnitTestAdapterUnloadIntegration"));

            // Oracle
            definitionList.Add(new("Oracle.DataAccess", "Oracle.DataAccess.Client.OracleCommand", "ExecuteDbDataReader",  new[] { "System.Data.Common.DbDataReader", "System.Data.CommandBehavior" }, 4, 122, 0, 4, 122, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorIntegration"));
            definitionList.Add(new("Oracle.DataAccess", "Oracle.DataAccess.Client.OracleCommand", "ExecuteNonQuery",  new[] { "System.Int32" }, 4, 122, 0, 4, 122, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteNonQueryIntegration"));
            definitionList.Add(new("Oracle.DataAccess", "Oracle.DataAccess.Client.OracleCommand", "ExecuteReader",  new[] { "Oracle.DataAccess.Client.OracleDataReader" }, 4, 122, 0, 4, 122, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderIntegration"));
            definitionList.Add(new("Oracle.DataAccess", "Oracle.DataAccess.Client.OracleCommand", "ExecuteReader",  new[] { "Oracle.DataAccess.Client.OracleDataReader", "System.Data.CommandBehavior" }, 4, 122, 0, 4, 122, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorIntegration"));
            definitionList.Add(new("Oracle.DataAccess", "Oracle.DataAccess.Client.OracleCommand", "ExecuteScalar",  new[] { "System.Object" }, 4, 122, 0, 4, 122, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteScalarIntegration"));
            definitionList.Add(new("Oracle.ManagedDataAccess", "Oracle.ManagedDataAccess.Client.OracleCommand", "ExecuteDbDataReader",  new[] { "System.Data.Common.DbDataReader", "System.Data.CommandBehavior" }, 4, 122, 0, 4, 122, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorIntegration"));
            definitionList.Add(new("Oracle.ManagedDataAccess", "Oracle.ManagedDataAccess.Client.OracleCommand", "ExecuteDbDataReader",  new[] { "System.Data.Common.DbDataReader", "System.Data.CommandBehavior" }, 2, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorIntegration"));
            definitionList.Add(new("Oracle.ManagedDataAccess", "Oracle.ManagedDataAccess.Client.OracleCommand", "ExecuteNonQuery",  new[] { "System.Int32" }, 4, 122, 0, 4, 122, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteNonQueryIntegration"));
            definitionList.Add(new("Oracle.ManagedDataAccess", "Oracle.ManagedDataAccess.Client.OracleCommand", "ExecuteNonQuery",  new[] { "System.Int32" }, 2, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteNonQueryIntegration"));
            definitionList.Add(new("Oracle.ManagedDataAccess", "Oracle.ManagedDataAccess.Client.OracleCommand", "ExecuteReader",  new[] { "Oracle.ManagedDataAccess.Client.OracleDataReader" }, 4, 122, 0, 4, 122, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderIntegration"));
            definitionList.Add(new("Oracle.ManagedDataAccess", "Oracle.ManagedDataAccess.Client.OracleCommand", "ExecuteReader",  new[] { "Oracle.ManagedDataAccess.Client.OracleDataReader" }, 2, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderIntegration"));
            definitionList.Add(new("Oracle.ManagedDataAccess", "Oracle.ManagedDataAccess.Client.OracleCommand", "ExecuteReader",  new[] { "Oracle.ManagedDataAccess.Client.OracleDataReader", "System.Data.CommandBehavior" }, 4, 122, 0, 4, 122, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorIntegration"));
            definitionList.Add(new("Oracle.ManagedDataAccess", "Oracle.ManagedDataAccess.Client.OracleCommand", "ExecuteReader",  new[] { "Oracle.ManagedDataAccess.Client.OracleDataReader", "System.Data.CommandBehavior" }, 2, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorIntegration"));
            definitionList.Add(new("Oracle.ManagedDataAccess", "Oracle.ManagedDataAccess.Client.OracleCommand", "ExecuteScalar",  new[] { "System.Object" }, 4, 122, 0, 4, 122, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteScalarIntegration"));
            definitionList.Add(new("Oracle.ManagedDataAccess", "Oracle.ManagedDataAccess.Client.OracleCommand", "ExecuteScalar",  new[] { "System.Object" }, 2, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteScalarIntegration"));

            // RabbitMQ
            definitionList.Add(new("RabbitMQ.Client", "RabbitMQ.Client.Events.EventingBasicConsumer", "HandleBasicDeliver",  new[] { "System.Void", "System.String", "System.UInt64", "System.Boolean", "System.String", "System.String", "RabbitMQ.Client.IBasicProperties", "_" }, 3, 6, 9, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.RabbitMQ.BasicDeliverIntegration"));
            definitionList.Add(new("RabbitMQ.Client", "RabbitMQ.Client.Framing.Impl.Model", "_Private_BasicPublish",  new[] { "System.Void", "System.String", "System.String", "System.Boolean", "RabbitMQ.Client.IBasicProperties", "_" }, 3, 6, 9, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.RabbitMQ.BasicPublishIntegration"));
            definitionList.Add(new("RabbitMQ.Client", "RabbitMQ.Client.Framing.Impl.Model", "_Private_ExchangeDeclare",  new[] { "System.Void", "System.String", "System.String", "System.Boolean", "System.Boolean", "System.Boolean", "System.Boolean", "System.Boolean", "System.Collections.Generic.IDictionary`2[System.String,System.Object]" }, 3, 6, 9, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.RabbitMQ.ExchangeDeclareIntegration"));
            definitionList.Add(new("RabbitMQ.Client", "RabbitMQ.Client.Framing.Impl.Model", "_Private_QueueDeclare",  new[] { "System.Void", "System.String", "System.Boolean", "System.Boolean", "System.Boolean", "System.Boolean", "System.Boolean", "System.Collections.Generic.IDictionary`2[System.String,System.Object]" }, 3, 6, 9, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.RabbitMQ.QueueDeclareIntegration"));
            definitionList.Add(new("RabbitMQ.Client", "RabbitMQ.Client.Impl.ModelBase", "BasicGet",  new[] { "RabbitMQ.Client.BasicGetResult", "System.String", "System.Boolean" }, 3, 6, 9, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.RabbitMQ.BasicGetIntegration"));
            definitionList.Add(new("RabbitMQ.Client", "RabbitMQ.Client.Impl.ModelBase", "QueueBind",  new[] { "System.Void", "System.String", "System.String", "System.String", "System.Collections.Generic.IDictionary`2[System.String,System.Object]" }, 3, 6, 9, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.RabbitMQ.QueueBindIntegration"));

            // Serilog
            definitionList.Add(new("Serilog", "Serilog.Core.Logger", "Dispatch",  new[] { "System.Void", "Serilog.Events.LogEvent" }, 2, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Logging.Serilog.LogsInjection.LoggerDispatchInstrumentation"));
            definitionList.Add(new("Serilog", "Serilog.Core.Pipeline.Logger", "Dispatch",  new[] { "System.Void", "Serilog.Events.LogEvent" }, 1, 4, 0, 1, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Logging.Serilog.LogsInjection.LoggerDispatchInstrumentation"));

            // ServiceStackRedis
            definitionList.Add(new("ServiceStack.Redis", "ServiceStack.Redis.RedisNativeClient", "SendReceive",  new[] { "T", "System.Byte[][]", "System.Func`1[!!0]", "System.Action`1[System.Func`1[!!0]]", "System.Boolean" }, 4, 0, 0, 5, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Redis.ServiceStack.RedisNativeClientSendReceiveIntegration"));

            // SqlClient
            definitionList.Add(new("Microsoft.Data.SqlClient", "Microsoft.Data.SqlClient.SqlCommand", "ExecuteDbDataReader",  new[] { "System.Data.Common.DbDataReader", "System.Data.CommandBehavior" }, 1, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorIntegration"));
            definitionList.Add(new("Microsoft.Data.SqlClient", "Microsoft.Data.SqlClient.SqlCommand", "ExecuteDbDataReaderAsync",  new[] { "System.Threading.Tasks.Task`1<System.Data.Common.DbDataReader>", "System.Data.CommandBehavior", "System.Threading.CancellationToken" }, 1, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorAndCancellationAsyncIntegration"));
            definitionList.Add(new("Microsoft.Data.SqlClient", "Microsoft.Data.SqlClient.SqlCommand", "ExecuteNonQuery",  new[] { "System.Int32" }, 1, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteNonQueryIntegration"));
            definitionList.Add(new("Microsoft.Data.SqlClient", "Microsoft.Data.SqlClient.SqlCommand", "ExecuteNonQueryAsync",  new[] { "System.Threading.Tasks.Task`1<System.Int32>", "System.Threading.CancellationToken" }, 1, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteNonQueryAsyncIntegration"));
            definitionList.Add(new("Microsoft.Data.SqlClient", "Microsoft.Data.SqlClient.SqlCommand", "ExecuteReader",  new[] { "Microsoft.Data.SqlClient.SqlDataReader" }, 1, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderIntegration"));
            definitionList.Add(new("Microsoft.Data.SqlClient", "Microsoft.Data.SqlClient.SqlCommand", "ExecuteReader",  new[] { "Microsoft.Data.SqlClient.SqlDataReader", "System.Data.CommandBehavior" }, 1, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorIntegration"));
            definitionList.Add(new("Microsoft.Data.SqlClient", "Microsoft.Data.SqlClient.SqlCommand", "ExecuteReaderAsync",  new[] { "System.Threading.Tasks.Task`1<Microsoft.Data.SqlClient.SqlDataReader>" }, 1, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderAsyncIntegration"));
            definitionList.Add(new("Microsoft.Data.SqlClient", "Microsoft.Data.SqlClient.SqlCommand", "ExecuteReaderAsync",  new[] { "System.Threading.Tasks.Task`1<Microsoft.Data.SqlClient.SqlDataReader>", "System.Threading.CancellationToken" }, 1, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithCancellationAsyncIntegration"));
            definitionList.Add(new("Microsoft.Data.SqlClient", "Microsoft.Data.SqlClient.SqlCommand", "ExecuteReaderAsync",  new[] { "System.Threading.Tasks.Task`1<Microsoft.Data.SqlClient.SqlDataReader>", "System.Data.CommandBehavior" }, 1, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorAsyncIntegration"));
            definitionList.Add(new("Microsoft.Data.SqlClient", "Microsoft.Data.SqlClient.SqlCommand", "ExecuteReaderAsync",  new[] { "System.Threading.Tasks.Task`1<Microsoft.Data.SqlClient.SqlDataReader>", "System.Data.CommandBehavior", "System.Threading.CancellationToken" }, 1, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorAndCancellationAsyncIntegration"));
            definitionList.Add(new("Microsoft.Data.SqlClient", "Microsoft.Data.SqlClient.SqlCommand", "ExecuteScalar",  new[] { "System.Object" }, 1, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteScalarIntegration"));
            definitionList.Add(new("Microsoft.Data.SqlClient", "Microsoft.Data.SqlClient.SqlCommand", "ExecuteScalarAsync",  new[] { "System.Threading.Tasks.Task`1<System.Object>", "System.Threading.CancellationToken" }, 1, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteScalarAsyncIntegration"));
            definitionList.Add(new("System.Data", "System.Data.SqlClient.SqlCommand", "ExecuteDbDataReader",  new[] { "System.Data.Common.DbDataReader", "System.Data.CommandBehavior" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorIntegration"));
            definitionList.Add(new("System.Data", "System.Data.SqlClient.SqlCommand", "ExecuteDbDataReaderAsync",  new[] { "System.Threading.Tasks.Task`1<System.Data.Common.DbDataReader>", "System.Data.CommandBehavior", "System.Threading.CancellationToken" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorAndCancellationAsyncIntegration"));
            definitionList.Add(new("System.Data", "System.Data.SqlClient.SqlCommand", "ExecuteNonQuery",  new[] { "System.Int32" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteNonQueryIntegration"));
            definitionList.Add(new("System.Data", "System.Data.SqlClient.SqlCommand", "ExecuteNonQueryAsync",  new[] { "System.Threading.Tasks.Task`1<System.Int32>", "System.Threading.CancellationToken" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteNonQueryAsyncIntegration"));
            definitionList.Add(new("System.Data", "System.Data.SqlClient.SqlCommand", "ExecuteReader",  new[] { "System.Data.SqlClient.SqlDataReader" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderIntegration"));
            definitionList.Add(new("System.Data", "System.Data.SqlClient.SqlCommand", "ExecuteReader",  new[] { "System.Data.SqlClient.SqlDataReader", "System.Data.CommandBehavior" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorIntegration"));
            definitionList.Add(new("System.Data", "System.Data.SqlClient.SqlCommand", "ExecuteReaderAsync",  new[] { "System.Threading.Tasks.Task`1<System.Data.SqlClient.SqlDataReader>", "System.Data.CommandBehavior", "System.Threading.CancellationToken" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorAndCancellationAsyncIntegration"));
            definitionList.Add(new("System.Data", "System.Data.SqlClient.SqlCommand", "ExecuteScalar",  new[] { "System.Object" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteScalarIntegration"));
            definitionList.Add(new("System.Data", "System.Data.SqlClient.SqlCommand", "ExecuteScalarAsync",  new[] { "System.Threading.Tasks.Task`1<System.Object>", "System.Threading.CancellationToken" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteScalarAsyncIntegration"));
            definitionList.Add(new("System.Data.SqlClient", "System.Data.SqlClient.SqlCommand", "ExecuteDbDataReader",  new[] { "System.Data.Common.DbDataReader", "System.Data.CommandBehavior" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorIntegration"));
            definitionList.Add(new("System.Data.SqlClient", "System.Data.SqlClient.SqlCommand", "ExecuteDbDataReaderAsync",  new[] { "System.Threading.Tasks.Task`1<System.Data.Common.DbDataReader>", "System.Data.CommandBehavior", "System.Threading.CancellationToken" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorAndCancellationAsyncIntegration"));
            definitionList.Add(new("System.Data.SqlClient", "System.Data.SqlClient.SqlCommand", "ExecuteNonQuery",  new[] { "System.Int32" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteNonQueryIntegration"));
            definitionList.Add(new("System.Data.SqlClient", "System.Data.SqlClient.SqlCommand", "ExecuteNonQueryAsync",  new[] { "System.Threading.Tasks.Task`1<System.Int32>", "System.Threading.CancellationToken" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteNonQueryAsyncIntegration"));
            definitionList.Add(new("System.Data.SqlClient", "System.Data.SqlClient.SqlCommand", "ExecuteReader",  new[] { "System.Data.SqlClient.SqlDataReader" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderIntegration"));
            definitionList.Add(new("System.Data.SqlClient", "System.Data.SqlClient.SqlCommand", "ExecuteReader",  new[] { "System.Data.SqlClient.SqlDataReader", "System.Data.CommandBehavior" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorIntegration"));
            definitionList.Add(new("System.Data.SqlClient", "System.Data.SqlClient.SqlCommand", "ExecuteReaderAsync",  new[] { "System.Threading.Tasks.Task`1<System.Data.SqlClient.SqlDataReader>", "System.Data.CommandBehavior", "System.Threading.CancellationToken" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorAndCancellationAsyncIntegration"));
            definitionList.Add(new("System.Data.SqlClient", "System.Data.SqlClient.SqlCommand", "ExecuteScalar",  new[] { "System.Object" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteScalarIntegration"));
            definitionList.Add(new("System.Data.SqlClient", "System.Data.SqlClient.SqlCommand", "ExecuteScalarAsync",  new[] { "System.Threading.Tasks.Task`1<System.Object>", "System.Threading.CancellationToken" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteScalarAsyncIntegration"));

            // Sqlite
            definitionList.Add(new("Microsoft.Data.Sqlite", "Microsoft.Data.Sqlite.SqliteCommand", "ExecuteDbDataReader",  new[] { "System.Data.Common.DbDataReader", "System.Data.CommandBehavior" }, 2, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorIntegration"));
            definitionList.Add(new("Microsoft.Data.Sqlite", "Microsoft.Data.Sqlite.SqliteCommand", "ExecuteDbDataReaderAsync",  new[] { "System.Threading.Tasks.Task`1<System.Data.Common.DbDataReader>", "System.Data.CommandBehavior", "System.Threading.CancellationToken" }, 2, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorAndCancellationAsyncIntegration"));
            definitionList.Add(new("Microsoft.Data.Sqlite", "Microsoft.Data.Sqlite.SqliteCommand", "ExecuteNonQuery",  new[] { "System.Int32" }, 2, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteNonQueryIntegration"));
            definitionList.Add(new("Microsoft.Data.Sqlite", "Microsoft.Data.Sqlite.SqliteCommand", "ExecuteReader",  new[] { "Microsoft.Data.Sqlite.SqliteDataReader" }, 2, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderIntegration"));
            definitionList.Add(new("Microsoft.Data.Sqlite", "Microsoft.Data.Sqlite.SqliteCommand", "ExecuteReader",  new[] { "Microsoft.Data.Sqlite.SqliteDataReader", "System.Data.CommandBehavior" }, 2, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorIntegration"));
            definitionList.Add(new("Microsoft.Data.Sqlite", "Microsoft.Data.Sqlite.SqliteCommand", "ExecuteReaderAsync",  new[] { "System.Threading.Tasks.Task`1<Microsoft.Data.Sqlite.SqliteDataReader>", "System.Data.CommandBehavior", "System.Threading.CancellationToken" }, 2, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorAndCancellationAsyncIntegration"));
            definitionList.Add(new("Microsoft.Data.Sqlite", "Microsoft.Data.Sqlite.SqliteCommand", "ExecuteScalar",  new[] { "System.Object" }, 2, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteScalarIntegration"));
            definitionList.Add(new("System.Data.SQLite", "System.Data.SQLite.SQLiteCommand", "ExecuteDbDataReader",  new[] { "System.Data.Common.DbDataReader", "System.Data.CommandBehavior" }, 1, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorIntegration"));
            definitionList.Add(new("System.Data.SQLite", "System.Data.SQLite.SQLiteCommand", "ExecuteNonQuery",  new[] { "System.Int32" }, 1, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteNonQueryIntegration"));
            definitionList.Add(new("System.Data.SQLite", "System.Data.SQLite.SQLiteCommand", "ExecuteNonQuery",  new[] { "System.Int32", "System.Data.CommandBehavior" }, 1, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteNonQueryWithBehaviorIntegration"));
            definitionList.Add(new("System.Data.SQLite", "System.Data.SQLite.SQLiteCommand", "ExecuteReader",  new[] { "System.Data.SQLite.SQLiteDataReader" }, 1, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderIntegration"));
            definitionList.Add(new("System.Data.SQLite", "System.Data.SQLite.SQLiteCommand", "ExecuteReader",  new[] { "System.Data.SQLite.SQLiteDataReader", "System.Data.CommandBehavior" }, 1, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorIntegration"));
            definitionList.Add(new("System.Data.SQLite", "System.Data.SQLite.SQLiteCommand", "ExecuteScalar",  new[] { "System.Object" }, 1, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteScalarIntegration"));
            definitionList.Add(new("System.Data.SQLite", "System.Data.SQLite.SQLiteCommand", "ExecuteScalar",  new[] { "System.Object", "System.Data.CommandBehavior" }, 1, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteScalarWithBehaviorIntegration"));

            // StackExchangeRedis
            definitionList.Add(new("StackExchange.Redis", "StackExchange.Redis.ConnectionMultiplexer", "ExecuteAsyncImpl",  new[] { "System.Threading.Tasks.Task`1<T>", "StackExchange.Redis.Message", "StackExchange.Redis.ResultProcessor`1[!!0]", "System.Object", "StackExchange.Redis.ServerEndPoint" }, 1, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Redis.StackExchange.ConnectionMultiplexerExecuteAsyncImplIntegration"));
            definitionList.Add(new("StackExchange.Redis", "StackExchange.Redis.ConnectionMultiplexer", "ExecuteSyncImpl",  new[] { "T", "StackExchange.Redis.Message", "StackExchange.Redis.ResultProcessor`1[!!0]", "StackExchange.Redis.ServerEndPoint" }, 1, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Redis.StackExchange.ConnectionMultiplexerExecuteSyncImplIntegration"));
            definitionList.Add(new("StackExchange.Redis", "StackExchange.Redis.RedisBase", "ExecuteAsync",  new[] { "System.Threading.Tasks.Task`1<T>", "StackExchange.Redis.Message", "StackExchange.Redis.ResultProcessor`1[!!0]", "StackExchange.Redis.ServerEndPoint" }, 1, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Redis.StackExchange.RedisExecuteAsyncIntegration"));
            definitionList.Add(new("StackExchange.Redis", "StackExchange.Redis.RedisBase", "ExecuteSync",  new[] { "T", "StackExchange.Redis.Message", "StackExchange.Redis.ResultProcessor`1[!!0]", "StackExchange.Redis.ServerEndPoint" }, 1, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Redis.StackExchange.RedisExecuteSyncIntegration"));
            definitionList.Add(new("StackExchange.Redis", "StackExchange.Redis.RedisBatch", "ExecuteAsync",  new[] { "System.Threading.Tasks.Task`1<T>", "StackExchange.Redis.Message", "StackExchange.Redis.ResultProcessor`1[!!0]", "StackExchange.Redis.ServerEndPoint" }, 1, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Redis.StackExchange.RedisExecuteAsyncIntegration"));
            definitionList.Add(new("StackExchange.Redis", "StackExchange.Redis.RedisTransaction", "ExecuteAsync",  new[] { "System.Threading.Tasks.Task`1<T>", "StackExchange.Redis.Message", "StackExchange.Redis.ResultProcessor`1[!!0]", "StackExchange.Redis.ServerEndPoint" }, 1, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Redis.StackExchange.RedisExecuteAsyncIntegration"));
            definitionList.Add(new("StackExchange.Redis.StrongName", "StackExchange.Redis.ConnectionMultiplexer", "ExecuteAsyncImpl",  new[] { "System.Threading.Tasks.Task`1<T>", "StackExchange.Redis.Message", "StackExchange.Redis.ResultProcessor`1[!!0]", "System.Object", "StackExchange.Redis.ServerEndPoint" }, 1, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Redis.StackExchange.ConnectionMultiplexerExecuteAsyncImplIntegration"));
            definitionList.Add(new("StackExchange.Redis.StrongName", "StackExchange.Redis.ConnectionMultiplexer", "ExecuteSyncImpl",  new[] { "T", "StackExchange.Redis.Message", "StackExchange.Redis.ResultProcessor`1[!!0]", "StackExchange.Redis.ServerEndPoint" }, 1, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Redis.StackExchange.ConnectionMultiplexerExecuteSyncImplIntegration"));
            definitionList.Add(new("StackExchange.Redis.StrongName", "StackExchange.Redis.RedisBase", "ExecuteAsync",  new[] { "System.Threading.Tasks.Task`1<T>", "StackExchange.Redis.Message", "StackExchange.Redis.ResultProcessor`1[!!0]", "StackExchange.Redis.ServerEndPoint" }, 1, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Redis.StackExchange.RedisExecuteAsyncIntegration"));
            definitionList.Add(new("StackExchange.Redis.StrongName", "StackExchange.Redis.RedisBase", "ExecuteSync",  new[] { "T", "StackExchange.Redis.Message", "StackExchange.Redis.ResultProcessor`1[!!0]", "StackExchange.Redis.ServerEndPoint" }, 1, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Redis.StackExchange.RedisExecuteSyncIntegration"));
            definitionList.Add(new("StackExchange.Redis.StrongName", "StackExchange.Redis.RedisBatch", "ExecuteAsync",  new[] { "System.Threading.Tasks.Task`1<T>", "StackExchange.Redis.Message", "StackExchange.Redis.ResultProcessor`1[!!0]", "StackExchange.Redis.ServerEndPoint" }, 1, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Redis.StackExchange.RedisExecuteAsyncIntegration"));
            definitionList.Add(new("StackExchange.Redis.StrongName", "StackExchange.Redis.RedisTransaction", "ExecuteAsync",  new[] { "System.Threading.Tasks.Task`1<T>", "StackExchange.Redis.Message", "StackExchange.Redis.ResultProcessor`1[!!0]", "StackExchange.Redis.ServerEndPoint" }, 1, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Redis.StackExchange.RedisExecuteAsyncIntegration"));

            // WebRequest
            definitionList.Add(new("System", "System.Net.HttpWebRequest", "BeginGetRequestStream",  new[] { "System.IAsyncResult", "System.AsyncCallback", "System.Object" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Http.WebRequest.HttpWebRequest_BeginGetRequestStream_Integration"));
            definitionList.Add(new("System", "System.Net.HttpWebRequest", "BeginGetResponse",  new[] { "System.IAsyncResult", "System.AsyncCallback", "System.Object" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Http.WebRequest.HttpWebRequest_BeginGetResponse_Integration"));
            definitionList.Add(new("System", "System.Net.HttpWebRequest", "EndGetResponse",  new[] { "System.Net.WebResponse", "System.IAsyncResult" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Http.WebRequest.HttpWebRequest_EndGetResponse_Integration"));
            definitionList.Add(new("System", "System.Net.HttpWebRequest", "GetRequestStream",  new[] { "System.IO.Stream" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Http.WebRequest.HttpWebRequest_GetRequestStream_Integration"));
            definitionList.Add(new("System", "System.Net.HttpWebRequest", "GetResponse",  new[] { "System.Net.WebResponse" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Http.WebRequest.HttpWebRequest_GetResponse_Integration"));
            definitionList.Add(new("System", "System.Net.WebRequest", "GetResponseAsync",  new[] { "System.Threading.Tasks.Task`1<System.Net.WebResponse>" }, 4, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Http.WebRequest.WebRequest_GetResponseAsync_Integration"));
            definitionList.Add(new("System.Net.Requests", "System.Net.HttpWebRequest", "BeginGetRequestStream",  new[] { "System.IAsyncResult", "System.AsyncCallback", "System.Object" }, 4, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Http.WebRequest.HttpWebRequest_BeginGetRequestStream_Integration"));
            definitionList.Add(new("System.Net.Requests", "System.Net.HttpWebRequest", "GetRequestStream",  new[] { "System.IO.Stream" }, 4, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Http.WebRequest.HttpWebRequest_GetRequestStream_Integration"));
            definitionList.Add(new("System.Net.Requests", "System.Net.HttpWebRequest", "GetResponse",  new[] { "System.Net.WebResponse" }, 4, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Http.WebRequest.HttpWebRequest_GetResponse_Integration"));
            definitionList.Add(new("System.Net.Requests", "System.Net.WebRequest", "GetResponseAsync",  new[] { "System.Threading.Tasks.Task`1<System.Net.WebResponse>" }, 4, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Http.WebRequest.WebRequest_GetResponseAsync_Integration"));

            // XUnit
            definitionList.Add(new("xunit.execution.desktop", "Xunit.Sdk.TestAssemblyFinished", ".ctor",  new[] { "System.Void", "_", "_", "_", "_", "_", "_" }, 2, 2, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Testing.XUnit.XUnitTestAssemblyFinishedCtorIntegration"));
            definitionList.Add(new("xunit.execution.desktop", "Xunit.Sdk.TestAssemblyRunner`1", "RunTestCollectionAsync",  new[] { "System.Threading.Tasks.Task`1<Xunit.Sdk.RunSummary>", "Xunit.Sdk.IMessageBus", "_", "_", "_" }, 2, 2, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Testing.XUnit.XUnitTestAssemblyRunnerRunTestCollectionAsyncIntegration"));
            definitionList.Add(new("xunit.execution.desktop", "Xunit.Sdk.TestInvoker`1", "RunAsync",  new[] { "System.Threading.Tasks.Task`1<System.Decimal>" }, 2, 2, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Testing.XUnit.XUnitTestInvokerRunAsyncIntegration"));
            definitionList.Add(new("xunit.execution.desktop", "Xunit.Sdk.TestRunner`1", "RunAsync",  new[] { "System.Threading.Tasks.Task`1<Xunit.Sdk.RunSummary>" }, 2, 2, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Testing.XUnit.XUnitTestRunnerRunAsyncIntegration"));
            definitionList.Add(new("xunit.execution.dotnet", "Xunit.Sdk.TestAssemblyFinished", ".ctor",  new[] { "System.Void", "_", "_", "_", "_", "_", "_" }, 2, 2, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Testing.XUnit.XUnitTestAssemblyFinishedCtorIntegration"));
            definitionList.Add(new("xunit.execution.dotnet", "Xunit.Sdk.TestAssemblyRunner`1", "RunTestCollectionAsync",  new[] { "System.Threading.Tasks.Task`1<Xunit.Sdk.RunSummary>", "Xunit.Sdk.IMessageBus", "_", "_", "_" }, 2, 2, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Testing.XUnit.XUnitTestAssemblyRunnerRunTestCollectionAsyncIntegration"));
            definitionList.Add(new("xunit.execution.dotnet", "Xunit.Sdk.TestInvoker`1", "RunAsync",  new[] { "System.Threading.Tasks.Task`1<System.Decimal>" }, 2, 2, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Testing.XUnit.XUnitTestInvokerRunAsyncIntegration"));
            definitionList.Add(new("xunit.execution.dotnet", "Xunit.Sdk.TestRunner`1", "RunAsync",  new[] { "System.Threading.Tasks.Task`1<Xunit.Sdk.RunSummary>" }, 2, 2, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.Testing.XUnit.XUnitTestRunnerRunAsyncIntegration"));

            return definitionList;
        }

        private static List<NativeCallTargetDefinition> GetDerivedDefinitionsList()
        {
            List<NativeCallTargetDefinition> definitionList = new List<NativeCallTargetDefinition>();

            // AdoNet
            definitionList.Add(new("netstandard", "System.Data.Common.DbCommand", "ExecuteDbDataReader",  new[] { "System.Data.Common.DbDataReader", "System.Data.CommandBehavior" }, 2, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorIntegration"));
            definitionList.Add(new("netstandard", "System.Data.Common.DbCommand", "ExecuteNonQuery",  new[] { "System.Int32" }, 2, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteNonQueryIntegration"));
            definitionList.Add(new("netstandard", "System.Data.Common.DbCommand", "ExecuteScalar",  new[] { "System.Object" }, 2, 0, 0, 2, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteScalarIntegration"));
            definitionList.Add(new("System.Data", "System.Data.Common.DbCommand", "ExecuteDbDataReader",  new[] { "System.Data.Common.DbDataReader", "System.Data.CommandBehavior" }, 2, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorIntegration"));
            definitionList.Add(new("System.Data", "System.Data.Common.DbCommand", "ExecuteNonQuery",  new[] { "System.Int32" }, 2, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteNonQueryIntegration"));
            definitionList.Add(new("System.Data", "System.Data.Common.DbCommand", "ExecuteScalar",  new[] { "System.Object" }, 2, 0, 0, 4, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteScalarIntegration"));
            definitionList.Add(new("System.Data.Common", "System.Data.Common.DbCommand", "ExecuteDbDataReader",  new[] { "System.Data.Common.DbDataReader", "System.Data.CommandBehavior" }, 4, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteReaderWithBehaviorIntegration"));
            definitionList.Add(new("System.Data.Common", "System.Data.Common.DbCommand", "ExecuteNonQuery",  new[] { "System.Int32" }, 4, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteNonQueryIntegration"));
            definitionList.Add(new("System.Data.Common", "System.Data.Common.DbCommand", "ExecuteScalar",  new[] { "System.Object" }, 4, 0, 0, 6, 65535, 65535, assemblyFullName, "Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.CommandExecuteScalarIntegration"));

            return definitionList;
        }
    }
}
