#ifndef BOOLEAN_OPERATION_VERIFIER_H
#define BOOLEAN_OPERATION_VERIFIER_H

/* Generated by flatcc 0.6.1 FlatBuffers schema compiler for C by dvide.com */

#ifndef BOOLEAN_OPERATION_READER_H
#include "boolean_operation_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"


#include "flatcc/flatcc_epilogue.h"
#endif /* BOOLEAN_OPERATION_VERIFIER_H */
