issuer: https://token.actions.githubusercontent.com

subject_pattern: "repo:DataDog/dd-trace-dotnet:ref:refs/heads/.+"

claim_pattern:
  event_name: (workflow_dispatch|milestone)
  repository: DataDog/dd-trace-dotnet
  job_workflow_ref: DataDog/dd-trace-dotnet/\.github/workflows/code_freeze_end\.yml@refs/heads/.+

permissions:
  issues: write
  statuses: write
  pull_requests: read
