issuer: https://token.actions.githubusercontent.com

subject_pattern: "repo:DataDog/dd-trace-dotnet:ref:refs/heads/.+"

claim_pattern:
  event_name: (workflow_dispatch|schedule)
  repository: DataDog/dd-trace-dotnet
  job_workflow_ref: DataDog/dd-trace-dotnet/\.github/workflows/auto_deploy_aas_test_apps\.yml@refs/heads/.+

permissions:
  issues: read
  actions: read
