<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!--These should be consolidated in a file that can be shared for the tests and samples directories -->
    <DefineConstants Condition="'$(BuildingInsideVisualStudio)'=='true' or '$(TestAllPackageVersions)'!='true'">$(DefineConstants);DEFAULT_SAMPLES</DefineConstants>
    <DefineConstants Condition="'$(TestAllPackageVersions)'=='true' AND '$(IncludeMinorPackageVersions)'=='true'">$(DefineConstants);TEST_ALL_MINOR_PACKAGE_VERSIONS</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="xunit.runner.json" />
    <Compile Include="..\Datadog.Trace.ClrProfiler.IntegrationTests\CI\**\*.cs" Link="CI\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\Datadog.Trace.ClrProfiler.IntegrationTests\SourceCodeIntegrationGitMetadataTests.cs" Link="SourceCodeIntegrationGitMetadataTests.cs" />
    <Compile Include="..\Datadog.Trace.ClrProfiler.IntegrationTests\GlobalUsings.cs" Link="GlobalUsings.cs" />
    <Compile Include="..\Datadog.Trace.ClrProfiler.IntegrationTests\Helpers\CombinatorialParams.cs" Link="Helpers\CombinatorialParams.cs" />
    <Compile Include="..\Datadog.Trace.ClrProfiler.IntegrationTests\Helpers\TelemetryHelper.cs" Link="Helpers\TelemetryHelper.cs" />
    <Compile Include="..\Datadog.Trace.ClrProfiler.IntegrationTests\PackageVersions.g.cs" Link="PackageVersions.g.cs" />
    <Compile Include="..\Datadog.Trace.ClrProfiler.IntegrationTests\PackageVersionsLatestMajors.g.cs" Link="PackageVersionsLatestMajors.g.cs" />
    <Compile Include="..\Datadog.Trace.ClrProfiler.IntegrationTests\PackageVersionsLatestMinors.g.cs" Link="PackageVersionsLatestMinors.g.cs" />
    <Compile Include="..\Datadog.Trace.ClrProfiler.IntegrationTests\PackageVersionsLatestSpecific.g.cs" Link="PackageVersionsLatestSpecific.g.cs" />
    <Compile Include="..\Datadog.Trace.TestHelpers.SharedSource\VerifyHelper.cs" Link="Helpers\VerifyHelper.cs" />
    <Content Include="..\Datadog.Trace.ClrProfiler.IntegrationTests\xunit.runner.json" Link="xunit.runner.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <ProjectReference Include="..\..\src\Datadog.Trace\Datadog.Trace.csproj" />
    <ProjectReference Include="..\Datadog.Trace.TestHelpers.AutoInstrumentation\Datadog.Trace.TestHelpers.AutoInstrumentation.csproj" />
    <ProjectReference Include="..\Datadog.Trace.TestHelpers\Datadog.Trace.TestHelpers.csproj" />

    <PackageReference Include="Microsoft.Diagnostics.Runtime" Version="2.0.226801" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
    <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="8.0.1" />
    <PackageReference Include="System.Collections.Immutable" Version="6.0.0" />
    <PackageReference Include="Testcontainers" Version="3.6.0" />
    <PackageReference Include="StrongNamer" Version="0.2.5" />
    <PackageReference Include="Verify.Xunit" Version="14.13.1" />
    <PackageReference Include="DiffPlex" Version="1.7.2" />
  </ItemGroup>

  <ItemGroup Condition=" $(TargetFramework.StartsWith('net4')) ">
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.EnterpriseServices" />
  </ItemGroup>

  <ItemGroup Condition=" $(TargetFramework.StartsWith('netcoreapp')) ">
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
  </ItemGroup>

</Project>
