//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
#pragma warning disable CS8600, CS8601, CS8602, CS8603, CS8604, CS8618, CS8620, CS8714, CS8762, CS8765, CS8766, CS8767, CS8768, CS8769, CS8612, CS8629, CS8774
// Decompiled with JetBrains decompiler
// Type: System.Reflection.Internal.ByteSequenceComparer
// Assembly: System.Reflection.Metadata, Version=7.0.0.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// MVID: 2EB35F4B-CF50-496F-AFB8-CC6F6F79CB72

using System;
using System.Collections.Generic;
using Datadog.Trace.VendoredMicrosoftCode.System.Collections.Immutable;

#nullable enable
namespace Datadog.Trace.VendoredMicrosoftCode.System.Reflection.Internal
{
    internal sealed class ByteSequenceComparer : 
    IEqualityComparer<byte[]>,
    IEqualityComparer<ImmutableArray<byte>>
  {
    internal static readonly ByteSequenceComparer Instance = new ByteSequenceComparer();

    private ByteSequenceComparer()
    {
    }

    internal static bool Equals(ImmutableArray<byte> x, ImmutableArray<byte> y) => MemoryExtensions.SequenceEqual<byte>(x.AsSpan(), y.AsSpan());

    internal static bool Equals(
      byte[] left,
      int leftStart,
      byte[] right,
      int rightStart,
      int length)
    {
      return MemoryExtensions.SequenceEqual<byte>(MemoryExtensions.AsSpan<byte>(left, leftStart, length), (MemoryExtensions.AsSpan<byte>(right, rightStart, length)));
    }

    internal static bool Equals(byte[]? left, byte[]? right) => MemoryExtensions.SequenceEqual<byte>(MemoryExtensions.AsSpan<byte>(left), (MemoryExtensions.AsSpan<byte>(right)));

    internal static int GetHashCode(byte[] x) => Hash.GetFNVHashCode((x));

    internal static int GetHashCode(ImmutableArray<byte> x) => Hash.GetFNVHashCode(x.AsSpan());


    #nullable disable
    bool IEqualityComparer<byte[]>.Equals(byte[] x, byte[] y) => ByteSequenceComparer.Equals(x, y);

    int IEqualityComparer<byte[]>.GetHashCode(byte[] x) => ByteSequenceComparer.GetHashCode(x);

    bool IEqualityComparer<ImmutableArray<byte>>.Equals(
      ImmutableArray<byte> x,
      ImmutableArray<byte> y)
    {
      return ByteSequenceComparer.Equals(x, y);
    }

    int IEqualityComparer<ImmutableArray<byte>>.GetHashCode(ImmutableArray<byte> x) => ByteSequenceComparer.GetHashCode(x);
  }
}
