//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
#pragma warning disable CS8600, CS8601, CS8602, CS8603, CS8604, CS8618, CS8620, CS8714, CS8762, CS8765, CS8766, CS8767, CS8768, CS8769, CS8612, CS8629, CS8774
#nullable enable
// Decompiled with JetBrains decompiler
// Type: System.Reflection.Internal.DecimalUtilities
// Assembly: System.Reflection.Metadata, Version=7.0.0.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// MVID: 2EB35F4B-CF50-496F-AFB8-CC6F6F79CB72

using System;

namespace Datadog.Trace.VendoredMicrosoftCode.System.Reflection.Internal
{
  internal static class DecimalUtilities
  {
    public static int GetScale(this Decimal value) => (int) (byte) (Decimal.GetBits(value)[3] >> 16);

    public static void GetBits(
      this Decimal value,
      out bool isNegative,
      out byte scale,
      out uint low,
      out uint mid,
      out uint high)
    {
      int[] bits = Decimal.GetBits(value);
      low = (uint) bits[0];
      mid = (uint) bits[1];
      high = (uint) bits[2];
      scale = (byte) (bits[3] >> 16);
      isNegative = ((ulong) bits[3] & 2147483648UL) > 0UL;
    }
  }
}
