//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
#pragma warning disable CS8600, CS8601, CS8602, CS8603, CS8604, CS8618, CS8620, CS8714, CS8762, CS8765, CS8766, CS8767, CS8768, CS8769, CS8612, CS8629, CS8774
// Decompiled with JetBrains decompiler
// Type: System.Reflection.Metadata.PathUtilities
// Assembly: System.Reflection.Metadata, Version=7.0.0.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// MVID: 2EB35F4B-CF50-496F-AFB8-CC6F6F79CB72

using System;
using System.IO;


#nullable enable
namespace Datadog.Trace.VendoredMicrosoftCode.System.Reflection.Metadata
{
    internal static class PathUtilities
  {
    private const char DirectorySeparatorChar = '\\';
    private const char AltDirectorySeparatorChar = '/';
    private const char VolumeSeparatorChar = ':';

    #nullable disable
    private static string s_platformSpecificDirectorySeparator;


    #nullable enable
    private static string PlatformSpecificDirectorySeparator
    {
      get
      {
        string directorySeparator = PathUtilities.s_platformSpecificDirectorySeparator;
        if (directorySeparator != null)
          return directorySeparator;
        char ch = Array.IndexOf<char>(Path.GetInvalidFileNameChars(), '*') >= 0 ? '\\' : '/';
        return PathUtilities.s_platformSpecificDirectorySeparator = ch.ToString();
      }
    }

    /// <summary>
    /// Returns the position in given path where the file name starts.
    /// </summary>
    /// <returns>-1 if path is null.</returns>
    internal static int IndexOfFileName(string path)
    {
      if (path == null)
        return -1;
      for (int index = path.Length - 1; index >= 0; --index)
      {
        switch (path[index])
        {
          case '/':
          case ':':
          case '\\':
            return index + 1;
          default:
            continue;
        }
      }
      return 0;
    }

    /// <summary>Get file name from path.</summary>
    /// <remarks>Unlike <see cref="M:System.IO.Path.GetFileName(System.String)" /> this method doesn't check for invalid path characters.</remarks>
    internal static string GetFileName(string path, bool includeExtension = true)
    {
      int startIndex = PathUtilities.IndexOfFileName(path);
      return startIndex > 0 ? path.Substring(startIndex) : path;
    }

    internal static string CombinePathWithRelativePath(string root, string relativePath)
    {
      if (root.Length == 0)
        return relativePath;
      switch (root[root.Length - 1])
      {
        case '/':
        case ':':
        case '\\':
          return root + relativePath;
        default:
          return root + PathUtilities.PlatformSpecificDirectorySeparator + relativePath;
      }
    }
  }
}
