//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, CS1591, CS1573, CS8018, SYSLIB0011, SYSLIB0032
#pragma warning disable CS8600, CS8601, CS8602, CS8603, CS8604, CS8618, CS8620, CS8714, CS8762, CS8765, CS8766, CS8767, CS8768, CS8769, CS8612, CS8629, CS8774
// Decompiled with JetBrains decompiler
// Type: System.Reflection.Internal.PooledStringBuilder
// Assembly: System.Reflection.Metadata, Version=7.0.0.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// MVID: 2EB35F4B-CF50-496F-AFB8-CC6F6F79CB72

using System;
using System.Text;


#nullable enable
namespace Datadog.Trace.VendoredMicrosoftCode.System.Reflection.Internal
{
    /// <summary>
    /// The usage is:
    ///        var inst = PooledStringBuilder.GetInstance();
    ///        var sb = inst.builder;
    ///        ... Do Stuff...
    ///        ... sb.ToString() ...
    ///        inst.Free();
    /// </summary>
    internal sealed class PooledStringBuilder
  {
    public readonly StringBuilder Builder = new StringBuilder();

    #nullable disable
    private readonly ObjectPool<PooledStringBuilder> _pool;
    private static readonly ObjectPool<PooledStringBuilder> s_poolInstance = PooledStringBuilder.CreatePool();

    private PooledStringBuilder(ObjectPool<PooledStringBuilder> pool) => this._pool = pool;

    public int Length => this.Builder.Length;

    public void Free()
    {
      StringBuilder builder = this.Builder;
      if (builder.Capacity > 1024)
        return;
      builder.Clear();
      this._pool.Free(this);
    }


    #nullable enable
    public string ToStringAndFree()
    {
      string stringAndFree = this.Builder.ToString();
      this.Free();
      return stringAndFree;
    }

    public static ObjectPool<PooledStringBuilder> CreatePool()
    {
      ObjectPool<PooledStringBuilder> pool = (ObjectPool<PooledStringBuilder>) null;
      pool = new ObjectPool<PooledStringBuilder>((Func<PooledStringBuilder>) (() => new PooledStringBuilder(pool)), 32);
      return pool;
    }

    public static PooledStringBuilder GetInstance() => PooledStringBuilder.s_poolInstance.Allocate();
  }
}
