name: Auto trigger AAS version bump

on:
  release:
    types: [published]

jobs:
  trigger_aas_release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required for dd-octo-sts OIDC token

    steps:
      - name: Get GitHub Token via dd-octo-sts
        id: octo-sts
        uses: DataDog/dd-octo-sts-action@acaa02eee7e3bb0839e4272dacb37b8f3b58ba80 # v1.0.3
        with:
          scope: DataDog/datadog-aas-extension
          policy: dd-trace-dotnet.github.trigger-aas-release

      - name: Trigger AAS release
        run: |
          curl -fX POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ steps.octo-sts.outputs.token }}" \
          https://api.github.com/repos/DataDog/datadog-aas-extension/dispatches \
          -d '{"event_type": "dd-trace-dotnet-release", "client_payload": {"is_prerelease":"${{github.event.release.prerelease}}", "version":"${{github.event.release.tag_name}}" } }'