//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
#pragma warning disable CS0618, CS0649, CS1574, CS1580, CS1581, CS1584, SYSLIB0011,SYSLIB0032
// dnlib: See LICENSE.txt for more info

namespace Datadog.Trace.Vendors.dnlib.DotNet.MD {
	/// <summary>
	/// Heap type. The values are set in stone by MS. Don't change.
	/// </summary>
	internal enum HeapType : uint {
		/// <summary>#Strings heap</summary>
		Strings	= 0,
		/// <summary>#GUID heap</summary>
		Guid	= 1,
		/// <summary>#Blob heap</summary>
		Blob	= 2,
		/// <summary>#US heap</summary>
		US		= 3,
	}
}
